### ISSUE TITLE
Fatal error: Failed to open stream

### ISSUE THREAD

**Issue by uSources** [JamesHeinrich/getID3#103]
Im using 1.9.13 version of getId3(), and when i try to load one song with embed cover, throws exception.

Warning: require_once(C:\Users\usour\Documents\PHP\untagged\vendor\phansys\getid3\GetId3\Lib\getid3.php): failed to open stream: No such file or directory in C:\Users\usour\Documents\PHP\untagged\vendor\phansys\getid3\GetId3\Lib\Helper.php on line 1571

Fatal error: require_once(): Failed opening required 'C:\Users\usour\Documents\PHP\untagged\vendor\phansys\getid3\GetId3\Lib\getid3.php' (include_path='.;C:\php\pear') in C:\Users\usour\Documents\PHP\untagged\vendor\phansys\getid3\GetId3\Lib\Helper.php on line 1571

**Comment by JamesHeinrich** [comment]
Since "Helper.php" is not part of getID3() it probably isn't a getID3() bug.
