### ISSUE TITLE
Error: unable to determine file format (HLS AAC audio-only)

### ISSUE THREAD

**Issue by radiantmediaplayer** [JamesHeinrich/getID3#104]
This is an AAC fragment (see https://www.radiantmedialyzer.net/test/good1.aac) from an audio-only HLS stream (http://www.lg73.ca/UHD/LG73/LG73.m3u8). It holds various ID3 information but when I try to read it with demo.basic.php I get an "error unable to determine file format".
Is is however able to read the first ID3 PRIV frame (see https://tools.ietf.org/html/draft-pantos-http-live-streaming-19#page-6). 

Any clue as to how to properly parse that file?

I also tried with the latest git but same issue.

**Comment by JamesHeinrich** [comment]
The firest 73 bytes are an ID3v2 tag, but it's just got an empty PRIV frame with ownerID of `com.apple.streaming.transportStreamTimestamp` (per your linked specs).
Following that spurious ID3v2 tag is the real ID3v2 tag with all the useful metadata, followed by the AAC data.
getID3 expects at most one ID3v2 tag at the beginning of the file, beyond which it looks for audio/video data, not more ID3v2 tags.
If you delete the first 73 bytes the file parses as expected.

**Comment by radiantmediaplayer** [comment]
@JamesHeinrich thanks for the quick answer and the great project. I understand now what is going on under the hood. I think we can manage the filtering of PRIV ID3 on our side when we get this kind of chunks.
