### ISSUE TITLE
Slow to get all information

### ISSUE THREAD

**Issue by shtse8** [JamesHeinrich/getID3#109]
I am analyzing a GIF information, but the `analyze` method returned all the data (>10MB) of GIF and took more than 3s. As I am using this project for my website, it's hard to process too long. Any idea to get only the useful information I needed instead? Thanks.

**Comment by JamesHeinrich** [comment]
You can comment-out the `case '!': // GIF Extension Block` switch section and see if that makes a speed improvement. You will of course lose the ability to detect animated GIFs, but you can see if that's the source of the slowdown.
