### ISSUE TITLE
Memory Limit might contain a space character (256 M)

### ISSUE THREAD

**Issue by marcoliverteschke** [JamesHeinrich/getID3#110]
I just moved a project using getID3 from an old server to a new environment (PHP 7) and got an error that the memory limit was below 4 MB.

getid3.php, line 133 checks whether the memory limit is formatted like "256M", but on the new server the value returned from php.ini was "256 M". Not sure if this was possible before PHP 7, but the format "Integer Space Letter" does not cause an error on the server level.

So I'd suggest changing

`		if (preg_match('#([0-9]+)M#i', $this->memory_limit, $matches)) {`

to 

`		if (preg_match('#([0-9]+)\ ?M#i', $this->memory_limit, $matches)) {`

**Comment by JamesHeinrich** [comment]
Thanks, changed in https://github.com/JamesHeinrich/getID3/commit/7fc5e5d7d3489113276755191b1fd0d56242fed1
