### ISSUE TITLE
Deadlock on incorrect QuickTime file

### ISSUE THREAD

**Issue by StudioMaX** [JamesHeinrich/getID3#111]
### File:
[deadf.zip](https://github.com/JamesHeinrich/getID3/files/1066488/deadf.zip)

### Probably related issues:
https://trac.ffmpeg.org/ticket/3866
http://www.getid3.org/phpBB3/viewtopic.php?f=7&t=836
http://www.getid3.org/phpBB3/viewtopic.php?t=1813

### Description:
After debugging a while I found that this file contain incorrect value in `number_entries` of the Atom `stsd` - for some reason this file has `08 00 00 01` instead of `00 00 00 01`.

I cannot play this file on my PC. But because of this error, the parsing of this file is looped to infinite.

**Comment by StudioMaX** [comment]
Proposed fix: https://github.com/JamesHeinrich/getID3/pull/112

**Comment by JamesHeinrich** [comment]
Fixed in https://github.com/JamesHeinrich/getID3/commit/335f54418367d3425f0061183cc00195374f9982
