### ISSUE TITLE
Mp3 Join

### ISSUE THREAD

**Issue by falconxxx** [JamesHeinrich/getID3#116]
I would like to know if its possible to get mp3 file's durations and combine another mp3 in the middle of it.

e.g  i have a mp3 file with 2 minutes anytime i run the script it should combine another mp3 file into the first 1minute

**Comment by JamesHeinrich** [comment]
If you want to _insert_ one mp3 file at a certain point in another one (e.g. A.mp3 is 2 mins long, and you want to insert B.mp3 at the 60-second mark, and then resume A when B is finished) then yes, that is easily done using https://github.com/JamesHeinrich/getID3/blob/master/demos/demo.joinmp3.php

If, however, you mean mixing the audio from A and B such that they play simultaneously (e.g. background intro music) then no, that's not possible. That would require decoding the mpeg audio, mixing the two audio streams, then re-encoding the combined audio stream as a new mp3, all of which is well outside the scope of getID3.
