### ISSUE TITLE
php is_writ(e)able, apache user, and network drives

### ISSUE THREAD

**Issue by ch1902** [JamesHeinrich/getID3#117]
On Windows, I run Apache as my admin user account and I also have my MP3 files saved on a network drive. On Windows, is_writable doesn't return the correct value for files that are in fact writable to group members, [see docs](http://php.net/manual/en/function.is-writable.php#61331). Since Windows ACL bugs are marked as WONTFIX, can getID3 be patched to check fileperms instead of simply relying on is_writable.

**Comment by JamesHeinrich** [comment]
Neat solution, thank you.
