### ISSUE TITLE
WWW → url_user → Mangled utf16/8?

### ISSUE THREAD

**Issue by Svish** [JamesHeinrich/getID3#119]
Tried setting the **WWW Extended Field**, using **Mp3tag v2.83**, to **`https://www.triangelos.net`**, and when I looked for it in the output from `getId3` I couldn't find it. Then I saw it was called **url_user**, but the content of it was mangled.

**How it looks in the tags array**

![capture](https://user-images.githubusercontent.com/142162/28824160-220679e2-76c1-11e7-956c-588d42c36ce9.PNG)

**How it looks in the "source"(?) array**

![capture2](https://user-images.githubusercontent.com/142162/28824172-2ffd00a2-76c1-11e7-939f-4cfa48711ef7.PNG)

Something not quite right happening in the copying there or something? 🤔

If it helps, I exported the resulting array using `var_export`: [var_export.txt](https://github.com/JamesHeinrich/getID3/files/1190498/var_export.txt)

**Comment by Svish** [comment]
Tried to use the **WOAR** (Official artist/performer webpage) Extended Field now, and there the text comes out correctly... 🤔

![capture](https://user-images.githubusercontent.com/142162/28824569-dd07dcf8-76c2-11e7-8347-34f032d0ca88.PNG)

**Comment by JamesHeinrich** [comment]
Can you send me a sample of the .mp3 so I can see what's happening, please?

**Comment by Svish** [comment]
Tried emailing you one now. 👍

**Comment by JamesHeinrich** [comment]
I have looked at the file and basically your tagger (Mp3tag v2.83) is broken. It's writing the WXXX (url_user) ID3v2 frame with a text encoding of UTF-16, but the data it's writing is ISO-8859-1 (or UTF-8, can't tell with this example).  getID3 sees the UTF-16 flag on the WXXX frame and parses the contents accordingly, and you end up with 13 (Chinese?) characters instead of 26 Latin characters.
The WOAR (url_artist) field, on the other hand, is written correctly, the encoding is set to ISO-8859-1 and the data is written accordingly, so it shows up correctly.
The data is written identically for both fields, it's just the encoding flag is incorrectly set on WXXX.

You may wish to report this to Mp3tag authors as a bug.

**Comment by Svish** [comment]
That makes sense. I've sent them an email about it. Thank you for looking into it 🙂

**Comment by Svish** [comment]
Got the following response, and seems the URL in W* frames are *supposed* to be written in ISO-8859-1 regardless of the encoding field, and that the encoding field is referring to the Description?

> Here is a quote from the [ID3v2.4 specification](http://id3.org/id3v2.4.0-frames):
>
>>4.3.2.   User defined URL link frame
>>
>>This frame is intended for URL [URL] links concerning the audio file
   in a similar way to the other "W"-frames. The frame body consists
   of a description of the string, represented as a terminated string,
   followed by the actual URL. The URL is always encoded with ISO-8859-1
   [ISO-8859-1]. There may be more than one "WXXX" frame in each tag,
   but only one with the same description.
>>
>>     <Header for 'User defined URL link frame', ID: "WXXX">
>>     Text encoding     $xx
>>     Description       <text string according to encoding> $00 (00)
>>     URL               <text string>
>>
>>So, I think what the PHP library you're attempting to use is ignoring, is that every user-defined URL link frame (WXXX) consists also of a text encoding flag and a – possible empty – description part. The text encoding flag is always written (in your example case it was set to 1, which means UTF-16 in ID3v2 parlance). An empty description part will still be written as a text string according to the encoding. In your case a UTF-16 BOM 0xFEFF followed by an terminating UTF-16 encoded null-character 0x0000. After that the URL is written as ISO-8859-1.

**Comment by JamesHeinrich** [comment]
Indeed, the Mp3tag authors are quite right. I have patched getID3 accordingly.
