### ISSUE TITLE
Engine and Collation

### ISSUE THREAD

**Issue by ropini** [JamesHeinrich/getID3#123]
After analyzing your code, I would like to ask you why do you set Collation and Engine and CharacterSet in your code (extension.cache.mysql.php)?

Since I am using databases with different engines and charsets, this is a bit problematic to me since comparison between charset can often result in errors.
*******************************************************************************
ENGINE=MyISAM CHARACTER SET=latin1 COLLATE=latin1_general_ci';
*******************************************************************************
So the real question is... is there any special reason for you to define collation and character set in the code?

**Comment by JamesHeinrich** [comment]
No, there is no special reason you need to use MyISAM or latin1, that's just what came up from SHOW CREATE TABLE at the time the extension was developed. I have removed that portion now.
