### ISSUE TITLE
WAV FILES

### ISSUE THREAD

**Issue by DMouse123** [JamesHeinrich/getID3#126]
HI There,

Thank you for this script ! I can change the meta data for an Mp3 - how do I do tis for a WAV ?

".....Failed to write tags!
Tag format "id3v2.3" is not allowed on "wav.wav" files...."

Thanks,

Cheers
Darren

**Comment by JamesHeinrich** [comment]
getID3 can read comments from a few RIFF.WAV extensions (e.g. bext, cart) but does not support writing any metadata to RIFF/WAV.
