### ISSUE TITLE
Problem writing lyrics in id3v2 caused by Grammar error 'unsychronised_lyric'

### ISSUE THREAD

**Issue by KeitelDOG** [JamesHeinrich/getID3#136]
https://github.com/JamesHeinrich/getID3/blob/e100cd3442465d40197eb61e30e56b8d16ba6ffa/getid3/write.id3v2.php#L1982

https://github.com/JamesHeinrich/getID3/blob/e100cd3442465d40197eb61e30e56b8d16ba6ffa/getid3/write.id3v2.php#L2057

Many people will have difficulties following the demo because when we put the key 'unsynchronised_lyrics', or 'unsynchronised_lyric' in $dataTags, it won't work.

Because the line 1982 and 2057 have misspelled the word unsynchronised with unsychronised.

I had headache since the day before yesterday, when I finally go hacking the codes I found them.

**Comment by JamesHeinrich** [comment]
Thanks. Fixed in https://github.com/JamesHeinrich/getID3/commit/1767b532cf07e220d81549a73a61530b111aa94d

The typo got in there because that's the way it was (and still is) written in the [ID3v2 v2.3 specifications document](http://id3.org/d3v2.3.0).

**Comment by KeitelDOG** [comment]
Oh great. Sorry for this, Thanks

**Comment by JamesHeinrich** [comment]
Nothing to be sorry about, thanks for catching the typo. It certainly makes more sense to spell it right :)
