### ISSUE TITLE
Genres like "90-er" are not recognized

### ISSUE THREAD

**Issue by Calliostro** [JamesHeinrich/getID3#137]
Hello,

If you have a MP3 file tagged like '80-er' (starting with a number), the tag is not recognized.
I found out, that this could be fixed, if the regex is changed in module.tag.id3v2.php line 533:

old:
`if (preg_match('#^[0-9]{1,3}#', $element)) {`

new:
`if (preg_match('#^[0-9]{1,3}$#', $element)) {`

But I'm not sure if there are side effects. Maybe you could check and commit a fix.

Thanks and regards
C.

**Comment by JamesHeinrich** [comment]
Thanks for the bug report. I have looked through and that is the correct fix.
Fixed in https://github.com/JamesHeinrich/getID3/commit/dda405440718ef78ef566a2666220e829bdfa8e3
