### ISSUE TITLE
Files on Windows network shares not readable

### ISSUE THREAD

**Issue by Calliostro** [JamesHeinrich/getID3#138]
Hello,

a file name like \\\\PC\Music\Test.mp3 is not accepted.

The v2.0 version scans the file successfully.

The difference is in getid3.php line 288.

Does not work:
`$filename = preg_replace('#(?<!gs:)('.preg_quote(DIRECTORY_SEPARATOR).'{2,})#', DIRECTORY_SEPARATOR, $filename);`

Works:
`$filename = preg_replace('#(.+)'.preg_quote(DIRECTORY_SEPARATOR).'{2,}#U', '\1'.DIRECTORY_SEPARATOR, $filename);`

Could you make it readable in the official 1.9.x branch as well?

Regards
C.

**Comment by Calliostro** [comment]
Sorry, I just saw you fixed it already in #2151

**Comment by JamesHeinrich** [comment]
Yes, already fixed in https://github.com/JamesHeinrich/getID3/commit/a6a5786ca32255fd36107dddcdda37e6f5d2bef2
