### ISSUE TITLE
setting ID3 tag before giving download of remote file

### ISSUE THREAD

**Issue by coolguruji** [JamesHeinrich/getID3#142]
Hi,

I am sorry if i am asking a stupid question!

I want to give download of a audio/mp4 file only contains audio from my server. I am able to do that. I am dont want to save it on my server
This is my php code that i am using.
$mp3path is a remote file on a server which is  mp4 file actually

        header('Content-Description: File Transfer');
        header('Content-length: ' . size($mp3path)); // size is a custom function
        header("Content-Type: audio/mpeg");	
        header('Content-Type: application/force-download');
        header('Content-Transfer-Encoding: binary'); 
        header('Content-disposition: attachment; filename="'.$title.'.mp3"'); 
        header('Connection: Keep-Alive');
        header('Expires: 0');
        header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
        header('Last-Modified: ' . gmdate('D, d M Y H:i:s', time()) . ' GMT');
        header("Cache-Control: private", false);
        header('Pragma: no-cache');
        readfile($mp3path);
        exit;

But i am facing a problem with the mp3 file that i am getting in that way, When i checked these files with some other mp3 checking programs i got to know that this file dont have bit-rate, sample rate, VBR etc so few of my users are reporting me that files is corrupted, maybe file is not playing on their devices.

How can i set these tags with your program without downloading file on my server?
I just want to set these values for the file via php before giving download
Is it possible?

**Comment by StudioMaX** [comment]
This library cannot encode audio files. It only allows to read/modify the ID3 tags (artist, title, etc.) but doesn't allow to modify MP3 frames (bitrate, sample rate, etc.).

**Comment by coolguruji** [comment]
Can you suggest me any command line program or php code by which i can set mp3 frames from a mp4 audio only file?

**Comment by JamesHeinrich** [comment]
MP3 and MP4 are totally different from each other, both audio format and container.

If you want to convert an MP4 to MP3 you'll need [something](https://askubuntu.com/questions/84584/converting-mp4-to-mp3) like [ffmpeg](https://en.wikipedia.org/wiki/FFmpeg), and a command-line like
`ffmpeg -i INPUT.MP4 -vn -acodec libmp3lame -ac 2 -ab 160k OUTPUT.MP3`

In any case, as _StudioMaX_ said, it's nothing getID3 can do.
