### ISSUE TITLE
Incompatible variable types in different places

### ISSUE THREAD

**Issue by StudioMaX** [JamesHeinrich/getID3#145]
This is the report by PHPStan after PHP type hints was imeplemented.
### getid3/getid3.lib.php
- [ ] Line 90: Casting to float something that's already float.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/getid3.lib.php#L90
- [ ] Line 100: Method getid3_lib::CastAsInt() should return int but returns float|int.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/getid3.lib.php#L100
- [ ] Line 241: Method getid3_lib::LittleEndian2Float() should return float but returns false|float.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/getid3.lib.php#L241
- [ ] Line 1499: Casting to float something that's already float.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/getid3.lib.php#L1499
---
### getid3/module.audio-video.flv.php
- [ ] Line 442: Method AMFStream::readByte() should return int but returns false|float|int.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio-video.flv.php#L442
- [ ] Line 463: Method AMFStream::readDouble() should return float but returns false|float.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio-video.flv.php#L463
--- 
### getid3/module.audio-video.matroska.php
- [ ] Line 1556: Method getid3_matroska::EBML2Int() should return int but returns false|float|int.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio-video.matroska.php#L1556
- [ ] Line 1887: Variable $stream might not be defined.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio-video.matroska.php#L1887
---
### getid3/module.audio-video.quicktime.php
- [ ] Line 2669: Call to function is_array() will always evaluate to false.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio-video.quicktime.php#L2669
---
### getid3/module.audio-video.riff.php
- [ ] Line 859: Array (array<string>) does not accept int.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio-video.riff.php#L859
- [ ] Line 864: Array (array<string>) does not accept int.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio-video.riff.php#L864
- [ ] Line 1921: Array (array<array>) does not accept string.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio-video.riff.php#L1921
- [ ] Line 2711: Method getid3_riff::EitherEndian2Int() should return int but returns false|float|int.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio-video.riff.php#L2711
- [ ] Line 2713: Method getid3_riff::EitherEndian2Int() should return int but returns false|float|int.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio-video.riff.php#L2713
---
### getid3/module.audio.midi.php
- [ ] Line 324: Variable $microsecondsperbeat might not be defined.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.audio.midi.php#L324
---
### getid3/module.graphic.tiff.php
- [ ] Line 196: Method getid3_tiff::TIFFendian2Int() should return false|int but returns false|float|int.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.graphic.tiff.php#L196
- [ ] Line 198: Method getid3_tiff::TIFFendian2Int() should return false|int but returns false|float|int.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.graphic.tiff.php#L198
---
### getid3/module.misc.iso.php
- [ ] Line 316: Array (array<array>) does not accept string.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.misc.iso.php#L316
---
### getid3/module.tag.lyrics3.php
- [ ] Line 157: Array (array<array<int>>) does not accept int.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/module.tag.lyrics3.php#L157
---
### getid3/write.php
- [ ] Line 318: Strict comparison using !== between array and false will always evaluate to true.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/write.php#L318
- [ ] Line 330: Strict comparison using !== between array and false will always evaluate to true.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/write.php#L330
- [ ] Line 346: Property getid3_write_id3v2::$tag_data (array) does not accept array|false.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/write.php#L346
- [ ] Line 358: Strict comparison using !== between array and false will always evaluate to true.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/write.php#L358
- [ ] Line 370: Strict comparison using !== between array and false will always evaluate to true.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/write.php#L370
- [ ] Line 382: Strict comparison using !== between array and false will always evaluate to true.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/write.php#L382
- [ ] Line 540: Array (array<int>) does not accept string.
https://github.com/JamesHeinrich/getID3/blob/34c8eaf2c670a1f319a6721e7ad09558382a28f2/getid3/write.php#L540

**Comment by JamesHeinrich** [comment]
How did you find this report? I guess I wasn't looking in the right place but I couldn't see the details of what was wrong, therefore I couldn't fix them.

Fixed most of them in https://github.com/JamesHeinrich/getID3/commit/59e9dcf42d74430a3c4a876df21b1059586a0db2

I am confused about a few "Array (array) does not accept string" errors, for things like `$something['key'] = 'abc';`
Why is that being flagged as an error? How should it be written?

**Comment by StudioMaX** [comment]
One note about
https://github.com/JamesHeinrich/getID3/blob/47a2e631a64076b612c85a515540e30e5406a59e/getid3/getid3.lib.php#L1488-L1500
Looks like this is false-positive error, because `$adjustment` won't be casted as float all the time (look https://3v4l.org/qZZ6q). May be changed to something like
```php
$adjustment = (float) ($rawadjustment / 10);
```

Everything else seems fixed 👍

**Comment by JamesHeinrich** [comment]
Changed in https://github.com/JamesHeinrich/getID3/commit/b2b3c5d27a2e6a001826e45baf7273e6b4ce6dc8

Thanks for your help.
