### ISSUE TITLE
MPEG-2 videos return wrong aspect ratio

### ISSUE THREAD

**Issue by brion** [JamesHeinrich/getID3#148]
Working on [adding MPEG-2 video upload to MediaWiki](https://phabricator.wikimedia.org/T166024) I noticed that getid3 on this MPEG-2 file https://archive.org/download/FolgersCoffe/FolgersCoffe.mpeg returns an incorrect `['video']['pixel_aspect_ratio']` of 0.6735, which is the MPEG-1 interpretation of the value 2 for the aspect ratio field.

In MPEG-2, the field should be interpreted differently, as a key to a list of display aspect ratios, in this case 2 mapping to 4:3 (see eg https://web.archive.org/web/20170910202756/http://dvd.sourceforge.net/dvdinfo/mpeghdrs.html )

Workaround: pull the raw field value out from `['mpeg']['video']['raw']['aspect_ratio_information']` and interpret it directly.

Recommended fix: if the file is found to be MPEG-2, calculate the correct pixel aspect ratio from the given size and the display aspect ratio key and override the MPEG-1 mapping.

**Comment by JamesHeinrich** [comment]
Since you're familiar with the issue, are you able to submit a patch to correct the issue?

**Comment by brion** [comment]
Yes, can do. :)

**Comment by JamesHeinrich** [comment]
Actually don't worry about it, the problem was simpler than I thought, so I've fixed it in https://github.com/JamesHeinrich/getID3/commit/97dd36020dd9850935f2054db563c1fec936b924

**Comment by brion** [comment]
One more tweak -- the MPEG-2 aspect ratios are display aspect ratios, not pixel aspect ratios, so the  value from the lookup table needs to be multiplied by I believe `$height / $width` to get a pixel aspect ratio.

**Comment by brion** [comment]
Specifically,  the value for square pixels should return a pixel aspect ratio of 1, while the other values need to be scaled from display aspect to pixel aspect.
