### ISSUE TITLE
how change mp3 tags ?

### ISSUE THREAD

**Issue by pooria-jahedi** [JamesHeinrich/getID3#153]
hi 
how i can change tags music ?

**Comment by StudioMaX** [comment]
Look this demo
https://github.com/JamesHeinrich/getID3/blob/master/demos/demo.simple.write.php

**Comment by ephod** [comment]
Hi, hello. I must change the README.md. This is a work in progress, lately, I've been working a lot, as soon as I have more time I will continue working on it. This package is going to be refactored. If you want to contribute, please feel free. Thanks @pooria-jahedi  and @StudioMaX
