### ISSUE TITLE
v2 branch

### ISSUE THREAD

**Issue by StudioMaX** [JamesHeinrich/getID3#154]
There was an v2 branch in this project, which I was used (and supported) in some projects. Today I've tried to update the composer dependencies and realized that this branch doesn't exist anymore...
This branch has more modern structure like namespaces, spl autoloaders (or Composer PSR-4 namespaces), removed global constants, etc. There was quite a lot of work done in the v2 branch, and it would be wrong to delete it just like that. It would be more logical to make it a stable branch, and set the current one to a legacy state. All of the code in v1 looks like a simple set of several .php files written in the PHP4 style. Maybe it's time to move forward?

**Comment by Gemorroj** [comment]
see:
https://github.com/JamesHeinrich/getID3/pull/26
https://github.com/JamesHeinrich/getID3/issues/45#issuecomment-115540426

**Comment by JamesHeinrich** [comment]
The so-called "v2" fork was an attempt by a former contributor to, as you say, modernize the codebase, the core of which was written around 2001-2002.  v2 was forked around 2004, with a flurry of activity for about a year, and then the branch author disappeared. Only a minority of features (30%? 40%?) were ever copied from v1.x to v2, and no changes after 2010 have been ported to the v2 branch. So the v2 branch may have been stylistically more modern, but the contents were terribly outdated.

If someone wants to fork from the current v1.9.x code and rework it into modern style with namespaces et al I think that would probably be a great idea, but I don't have the inspiration to work on it myself.

**Comment by StudioMaX** [comment]
Perhaps you are confusing the old v2 made before 2010 with the new one v2 made by @duncan3dc and which I synchronized with the current 1.9 one year ago (https://github.com/JamesHeinrich/getID3/pull/93).

**Comment by JamesHeinrich** [comment]
My apologies, I had completely forgotten that any updates had been done on the v2 branch since 2010.

I have granted you contributor access, please feel free to re-create the v2 branch with your latest code.

**Comment by StudioMaX** [comment]
Thanks, no problem. I will restore the codebase from my previous PR. Locally I have more updates from the v1.9 branch which I tried to update at the beginning of this year, will check and commit them later.

**Comment by StudioMaX** [comment]
Restored this branch to the state as it was in https://github.com/JamesHeinrich/getID3/pull/93
