### ISSUE TITLE
Invalid argument supplied for foreach() [ROOT/vendor/james-heinrich/getid3/getid3/getid3.php, line 1238]

### ISSUE THREAD

**Issue by mspeener** [JamesHeinrich/getID3#157]
Happens here:

```
foreach ($this->info[$comment_name]['comments'] as $tag_key => $valuearray) {
					foreach ($valuearray as $key => $value) {
```

This is the contents of $this->info[$comment_name]['comments']

```
[
	'encoding_tool' => [
		(int) 0 => 'Lavf57.71.100'
	],
	'gps_flags' => (int) 0,
	'gps_lang' => (int) 5575,
	'gps_location' => '',
	'gps_role' => (int) 0,
	'gps_longitude' => (float) 65422.422012329,
	'gps_latitude' => (float) 37.110198974609,
	'gps_altitude' => (float) 0,
	'gps_body' => 'earth',
	'gps_notes' => ''
]
```

Should those gps values be under a gps key? They are added in module.audio-video.quicktime.php line 1702.

**Comment by StudioMaX** [comment]
Could you provide the entire error message and the sample file on which this error appears?

**Comment by JamesHeinrich** [comment]
@mspeener: You must be using an old version of getID3 because the line numbers don't match, but I'm able to replicate the problem with one of my own test files. Investigating...

**Comment by mspeener** [comment]
The error message is:

`Invalid argument supplied for foreach() [ROOT/vendor/james-heinrich/getid3/getid3/getid3.php, line 1238]`

I happens about 5-6 times in the one file.

The file the causes the error is at https://s3.us-west-2.amazonaws.com/artibucket.helloarti.com/video/Other%20Backroom%20Boys.mp4.

**Comment by JamesHeinrich** [comment]
Fixed in https://github.com/JamesHeinrich/getID3/commit/4d295e706cb7ff62ef93d1e695d48b59be351e60
