### ISSUE TITLE
Class getID3 should begin with capital letter.

### ISSUE THREAD

**Issue by damianprzygodzki** [JamesHeinrich/getID3#165]
It might be problem in lot of cases, with case-sensitive systems or even habits of developer.
Class should be named with capital letter.

**Comment by JamesHeinrich** [comment]
Who says that class names should begin with a capital letter?

**Comment by damianprzygodzki** [comment]
You asked a question and didn't even wait for answer. Thank You for support.

**Comment by StudioMaX** [comment]
> It might be problem in lot of cases

Any case? getID3 1.x don't follow any PSR and not using the SPL autoloading.
