### ISSUE TITLE
Ogg FLAC not parsed

### ISSUE THREAD

**Issue by charlemagnelasse** [JamesHeinrich/getID3#168]
See https://github.com/Rello/audioplayer/issues/340

**Comment by JamesHeinrich** [comment]
It's a format I haven't seen before:
https://xiph.org/flac/ogg_mapping.html

I'm looking into how to parse it.

**Comment by JamesHeinrich** [comment]
Should be fixed in https://github.com/JamesHeinrich/getID3/commit/17461949907103a68d0390103c50962618d318a4

**Comment by StudioMaX** [comment]
@JamesHeinrich Maybe it's time to release a new version? v1.9.15 was released on 27 Oct 2017. But this requires a changelog for all changes since the last stable version...

**Comment by Rello** [comment]
@JamesHeinrich adding to the pre question: will there be a new release or is the current paster stable to be used as is?
