### ISSUE TITLE
Chapter Images

### ISSUE THREAD

**Issue by sull** [JamesHeinrich/getID3#170]
It does not look like chapter images are supported. Any plan to add support?

**Comment by JamesHeinrich** [comment]
If you wish to provide a sample file that demonstrates the chapter images then I can take a look.

**Comment by sull** [comment]
Sure, this one has a few chapter images:
[
http://traffic.libsyn.com/atpfm/atp293.mp3?download=true](http://traffic.libsyn.com/atpfm/atp293.mp3?download=true)

**Comment by JamesHeinrich** [comment]
Thanks for the sample. Support for WXXX and APIC subframes in ID3v2 chapters added in 
https://github.com/JamesHeinrich/getID3/commit/198b3b63e6d9686c514b6b7923020e6266642b75

The [id3v2][chapters] structure now may contain "chapter_url" which is an array of WXXX associated with that chapter with the array key being the URL description (in your sample file there is a single URL for each chapter and they all have the generic description "chapter url"), but it's possible to have more than one URL per chapter (with a unique description).
For the attached pictures I chose not to duplicate the data in the returned structure (by having the image data in both its natural ID3v2 location and in [chapters], but there is a boolean [picture_present] flag in [chapters] to indicate that an attached picture is present and you should go looking for it in [id3v2][CHAP][<chap#>][subframes][?][data] (iterate through and find where [id3v2][CHAP][<chap#>][subframes][?][name] == 'APIC')

**Comment by sull** [comment]
Thanks for enhancing, i'll take a look.
