### ISSUE TITLE
TIFF - comments lost after image resize

### ISSUE THREAD

**Issue by luku** [JamesHeinrich/getID3#174]
Hi, I noticed that after resizing TIFF via imagemagick I can no longer extract some metadata.  

[sample.tif](https://drive.google.com/open?id=1wuKffqR-fx_0qhjmVQlDZhxldjfZZBPI) is the original file. It contains some metadata and your library extracted *comments/imagedescription*, *comments/software* and *comments_html/imagedescription*, *comments_html/software*.

[sample-resized.tif](https://drive.google.com/open?id=1IIclIlx96sj6bh55DtKXj5k2q4yxrY3u) is the resized file. It was created with imagemagick (ImageMagick 6.8.9-9 Q16 x86_64) cmd: `convert sample.tif -resize 1900x1900> sample-resized.tif`
It's not possible to extract the same metadata, but I can see in Adobe Bridge that the metadata are still there. Any idea what is the problem or difference between those 2 files or why it's not extracting the comments any more?

**Comment by JamesHeinrich** [comment]
Both files contain some `<x:xmpmeta>` XML metadata, presumably from Adobe Bridge. This data is not currently parsed by getID3.
The original file also contains a TIFF comment, but the resized file does not. I'm not sure if there is an ImageMagick option to copy/preserve TIFF comments.

I'll take a look when I have a moment to see how easy it would be to extract the Adobe metadata.

**Comment by luku** [comment]
Thanks for quick reply! I couldn't find any argument for preserving comments, but I found one post about similar issue, when [converting tiff to jpg](http://www.imagemagick.org/discourse-server/viewtopic.php?t=30390). I can also confirm, there're errors from IM: `Incompatible type for "RichTIFFIPTC"; tag ignored. 'TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/881.`
So it's probably that those tags are not recognized by IM and stripped, nothing strange in getID3. 

But it would be great feature, if it's possible to implement Adobe metadata extraction!

**Comment by JamesHeinrich** [comment]
I have improved TIFF parsing in https://github.com/JamesHeinrich/getID3/commit/1e6b2efd52ff75661900dca65e80f0e7161fd5fe

The XMP data, if available, is returned in `[TIFF][XMP]` but not parsed further; I leave that to the user if it's useful to them.

I also made a number of other small bugfixes in the TIFF module while I was there (unknown compression types, unhandled tag types, etc).
