### ISSUE TITLE
Memory Exhausted Error - M4V Videos (H.264)

### ISSUE THREAD

**Issue by davidhill001** [JamesHeinrich/getID3#177]
When I upload a 61.9MB M4V video I receive a memory exhausted error.

Video Details
Extension: m4v
Dimensions: 960 × 540
Codecs: H.264, AAC
Duration: 01:59

I have tried v1.9.16 and receive the following message:
PHP Fatal error:  Allowed memory size of 33554432 bytes exhausted (tried to allocate 33554464 bytes) in /vendor/james-heinrich/getid3/getid3/getid3.php on line 1982

I have also tried with the dev-master and get the message but caused by a different line:
PHP Fatal error:  Allowed memory size of 33554432 bytes exhausted (tried to allocate 33554464 bytes) in /vendor/james-heinrich/getid3/getid3/getid3.php on line 1991

I am using PHP 7.1.8 with the PHP Memory Limit set at 32MB.

**Comment by JamesHeinrich** [comment]
The first and obvious solution would be to increase the PHP memory_limit to something larger, like 128MB or more. 32MB is very restrictive.  Just above the quoted line is a check that is supposed to catch this, but in your case it just missed catching it by 32 bytes. I have adjusted that check slightly.

I'm not sure how possible it is to optimize memory usage further for quicktime videos. If you want me to investigate further please provide a link (either here or to info@getid3.org) to this (or similar) sample file that trips up with 32MB PHP memory_limit and I'll see where's having the problem, but no promises it can be optimized to fit into that limited memory space.

**Comment by markfili** [comment]
In my case, updating to version 1.9.17 fixed the problem without altering the php.ini file.
