### ISSUE TITLE
getID3 converts songfile embedded picture to HTML

### ISSUE THREAD

**Issue by Nizhile** [JamesHeinrich/getID3#178]
Working on a performance problem at sonerezh/sonerezh#354, I noticed that getID3 makes some effort to convert the full `comments['picture']` to HTML. Then the converted string is removed from the `infos['comment_html']`.
I guess applications usually set `option_tags_html` to `false` (default is `true`). Anyway, this seems to be a bug in `getID3.HandleAllTags()`.

**Comment by JamesHeinrich** [comment]
Thanks, fixed in https://github.com/JamesHeinrich/getID3/issues/178
