### ISSUE TITLE
Decode chapter data

### ISSUE THREAD

**Issue by pierrocknroll** [JamesHeinrich/getID3#180]
Hi and thanks a lot for your great tool,

Auphonic and others services add an image and an url in theirs chapters and I'm wondering how to decode this.

In the array ['id3v2']['CHAP'], for each chapter there is a binary in 'data' but I don't know how to extract the image and the URL in this. 
The binary seems to start with the image and end with the URL.

You can try with their example file :
https://auphonic.com/media/blog/auphonic_chapters_demo.mp3

Thanks

**Comment by pierrocknroll** [comment]
Oh, I just that the master branch has more data ('chapter_url', 'picture_present') than 1.9 tag, I installed with composer.
Can you please make a release :) ?

**Comment by JamesHeinrich** [comment]
Special for you:
https://github.com/JamesHeinrich/getID3/releases/tag/v1.9.17

**Comment by pierrocknroll** [comment]
Thank you so much !
