### ISSUE TITLE
[Proposal] Reduce information for GIF files with $option_extra_info

### ISSUE THREAD

**Issue by RobertLang** [JamesHeinrich/getID3#183]
Hi,
when using getID3 to store meta information on different file formats I noticed that the information returned for GIF files is way too large and it takes quite some time.

Wouldn't it make sense to use the `$option_extra_info` (or another option) to skip information on `global_color_table` and `extension_blocks` to make processing more efficient?

Thanks for considering.

**Comment by JamesHeinrich** [comment]
The `global_color_table` still needs to be read/skipped (although parsing it into actual table values is not required). `extension_blocks` need to be parsed to check whether the GIF is animated or not.
However I can make it not return that data if `option_extra_info` is false. You might save a millisecond or two by not expanding the global color table, but it's not a whole lot faster.
Changed in https://github.com/JamesHeinrich/getID3/commit/fe4e0a590963e4733d145816c488d11b48e17850
