### ISSUE TITLE
Invalid regex pattern

### ISSUE THREAD

**Issue by ckressibucher** [JamesHeinrich/getID3#184]
When analyzing an MP3 with an id3v1 comment, I get a PHP Warning:

```
PHP Warning:  preg_match(): Compilation failed: escape sequence is invalid in character class at offset 16 in $VENDOR/james-heinrich/getid3/getid3/module.tag.id3v1.php on line 71
```

I guess, there is an `x` missing, so `\\B8` should probably be `\\xB8`.

**Comment by JamesHeinrich** [comment]
Thanks. I have no idea how long that typo has been there, must be a long time.
Fixed in https://github.com/JamesHeinrich/getID3/commit/68ef47e5bdebf927a7577961a419525b5e1bdb40
