### ISSUE TITLE
(again) false UTF-16 <BOM> and no termination strings

### ISSUE THREAD

**Issue by kuerbis42** [JamesHeinrich/getID3#189]
Hi James,
after writing my own little class - 'cause I didn't found your class :-( - I've had the same issue with UTF-16 and BOM.

Now I installed your class to try it out (07.06.19) and I tried it with my "favorit malformed mp3" files.
When I make a hexdump to that mp3, the follwing values are found:
`.. .. 54 41 4C 42 00 00 00 03 00 00 01 FF FE 43 4F 4D 4D 00 00 00 08 00 00 01 00 00 00 00 00 FF FE 00 00 .. ..`
These are the following frames: 
TALB (len 3)(no flags) 0x01 0xFF 0xFE
directly followed by 
COMM (len 8)(no flags) 0x01 0x00 0x00 0x00 0x00 0x00 0xFF 0xFE

For my class, I specially check on (yes, this is not a valid php-code ;-)
`strlen($value)==3 && ($value=="0x01 0xFF 0xFE"||$value=="0x01 0xFE 0xFF") ` (check encoding and &lt;BOM&gt;)
and if true, there is no termination and I clear the $value.
You did similar here: [ID3v2 remove BOM from frame descriptions ](https://github.com/JamesHeinrich/getID3/commit/88d284f7a2dbc014fe349e4efdb41d73faa0eb34) 

If I check this mp3 with your class, I get 

> album | array (1) | 0 string (2) �� 
> comment | array (1) | 0 string (2) �� 

so, your fix doesn't work here (in this mp3 there are a few more <BOM> in the returned array) - If you need it for exam, I'll send you a PM.
Greets, Frank

**Comment by JamesHeinrich** [comment]
Please send me a sample file to info@getid3.org

**Comment by kuerbis42** [comment]
Did you get the sample?

**Comment by JamesHeinrich** [comment]
I did receive the sample, thank you. I have not had a chance to look at it yet, but I will.

**Comment by JamesHeinrich** [comment]
Should be fixed in https://github.com/JamesHeinrich/getID3/commit/59ded880cc36fc228c17da40d9cd6c5a1b25b7a3
