### ISSUE TITLE
Please i need voice function joinmp3.php like mehmitag.com

### ISSUE THREAD

**Issue by Best9jamusic** [JamesHeinrich/getID3#190]
Please i need voice tag function joinmp3.php like mehmitag.com
here is my site mp3tag [http://best9jamusic.com.ng/mp3tag](http://best9jamusic.com.ng/mp3tag)
but voice tag not adding
thanks for your help
eg:

here is my fuction joinmp3 Below

```
<?php
// Mp3 Tag Editor
// Damnidea.com

// sample usage:

function CombineMultipleMP3sTo($FilenameOut, $FilenamesIn) {

	foreach ($FilenamesIn as $nextinputfilename) {
		if (!is_readable($nextinputfilename)) {
			echo 'Cannot read "'.$nextinputfilename.'"<BR>';
			return false;
		}
	}
	if (!is_writeable($FilenameOut)) {
	$handle =	fopen($FilenameOut,'w');
    if($handle)
    {
    fclose($handle);
    }
	}

	require_once('getid3/getid3.php');
	ob_start();
	if ($fp_output = fopen($FilenameOut, 'wb')) {

		ob_end_clean();
		// Initialize getID3 engine
		$getID3 = new getID3;
		foreach ($FilenamesIn as $nextinputfilename) {

			$CurrentFileInfo = $getID3->analyze($nextinputfilename);
			if ($CurrentFileInfo['fileformat'] == 'mp3') {

				ob_start();
				if ($fp_source = fopen($nextinputfilename, 'rb')) {

					ob_end_clean();
					$CurrentOutputPosition = ftell($fp_output);

					// copy audio data from first file
					fseek($fp_source, $CurrentFileInfo['avdataoffset'], SEEK_SET);
					while (!feof($fp_source) && (ftell($fp_source) < $CurrentFileInfo['avdataend'])) {
						fwrite($fp_output, fread($fp_source, 32768));
					}
					fclose($fp_source);

					// trim post-audio data (if any) copied from first file that we don't need or want
					$EndOfFileOffset = $CurrentOutputPosition + ($CurrentFileInfo['avdataend'] - $CurrentFileInfo['avdataoffset']);
					fseek($fp_output, $EndOfFileOffset, SEEK_SET);
					ftruncate($fp_output, $EndOfFileOffset);

				} else {

					$errormessage = ob_get_contents();
					ob_end_clean();
					echo 'failed to open '.$nextinputfilename.' for reading';
					fclose($fp_output);
					return false;

				}

			} else {

				echo $nextinputfilename.' is not MP3 format';
				fclose($fp_output);
				return false;

			}

		}

	} else {

		$errormessage = ob_get_contents();
		ob_end_clean();
		echo 'failed to open '.$FilenameOut.' for writing';
		return false;

	}

	fclose($fp_output);
	return true;
}

```

Here is mehmitag.com little code Below
Add voice Track On `<input type="text" name="mp3_voicetrack" value="" id="voicetag" class="input" style="width:190px;" /><select name="mp3_voice_track_add" class="select" style="width:60px;-webkit-appearance: none;-moz-appearance: none; -ms-appearance:none; -o-appearance: none;"><option value="">None</option><option value="mix-fcl">Mix First-Center-Last</option><option value="mix-first">Mix In First-</option><option value="mix-center">Mix In -Center-</option><option value="mix-last">Mix In -Last</option><option value="mix-fl">Mix In First-Last</option><option value="mix-cl">Mix In -Center-Last</option><option value="mix-fce">Mix First-Center-End</option><option value="mix-sce">Mix Start-Center-End</option><option value="mix-s">Mix Start-</option><option value="mix-e">Mix -End</option><option value="mix-se">Mix Start-End</option><option value="first">Join First -</option><option value="last">Join - Last</option><option value="first-last">Join First - Last</option></select>`

**Comment by JamesHeinrich** [comment]
I'm not sure what this question is asking. I'll close it now, if it's still an issue please reopen with a better explanation of what you're trying to do.
