### ISSUE TITLE
Unsupported operand types module.audio.ac3.php:763

### ISSUE THREAD

**Issue by lopezpaul** [JamesHeinrich/getID3#191]
PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/getID3/getid3/module.audio.ac3.php:763
Stack trace:
#0 /var/www/getID3/getid3/module.audio.ac3.php(441): getid3_ac3::frameSizeLookup(17, 1)
#1 /var/www/getID3/getid3/module.audio-video.matroska.php(380): getid3_ac3->Analyze()
#2 /var/www/getID3/getid3/getid3.php(623): getid3_matroska->Analyze()
#3 /var/www/test.php(15): getID3->analyze('/home/something....')

I debugged and found that reading the video.mkv and trying to analyze it in that variable has an arrangement but in line 763 it tries to add 2, however you can not add a number to an array, so what I did was add a condition before:

if (is_array ($ frameSizeLookup [$ frmsizecod])) {
    $ frameSizeLookup [$ frmsizecod] [0] + = 2;
} else {
    $ frameSizeLookup [$ frmsizecod] + = 2;// LINE 763 fix
}

I hope it works for other people and future repository updates

**Comment by JamesHeinrich** [comment]
Are you able to provide a small sample file that triggers this error?

**Comment by lopezpaul** [comment]
Download this [mkv video](https://tinyurl.com/y4zaw7yh) and try to run the Analize function and you will get the error.

I think that because the video has 2 audio tracks, if you allow me I can contribute with the fix, I already have the pull request ready.

**Comment by JamesHeinrich** [comment]
Not exactly a "small" file, and I edited your comment to remove the URL, but even with that sample file I cannot trigger the error. Nevertheless, the code is still broken. I have applied a different fix https://github.com/JamesHeinrich/getID3/commit/459ce620dc7e17764eb56dcc216cae084d03a6be because your fix might suppress the warning but doesn't fix the underlying logic error.

**Comment by lopezpaul** [comment]
Ok, thank you James.
