### ISSUE TITLE
wrong playtime string value

### ISSUE THREAD

**Issue by davideperi** [JamesHeinrich/getID3#193]
Hi there!

I'm using james-heinrich/getid3 version 1.9.

When I'm trying to extract information from this Mp3 file 

[episode1.mp3.zip](https://github.com/JamesHeinrich/getID3/files/3387814/episode1.mp3.zip)

I got a wrong duration time.

![Schermata 2019-07-12 alle 12 51 07](https://user-images.githubusercontent.com/2995481/61154774-dd3e8f80-a4a3-11e9-9900-22d1f788dc29.png)

I got 6 min instead of 20 min (if I play the mp3 with itunes for example).

Maybe is it a bug?

Regards.

**Comment by JamesHeinrich** [comment]
No bug (in getID3 anyways), the file you posted is actually truncated at 6:14
The VBR header in the file claims that the file is 45,858,159 bytes (it is actually only 12,095,488 bytes)
The VBR header in the file claims 54,334 audio frames, it actually only contains 14,324 audio frames.

The original file is 23:39 long, but you only have about 26% of it.
