### ISSUE TITLE
[Support] Fatal error

### ISSUE THREAD

**Issue by tenleftfingers** [JamesHeinrich/getID3#199]
(Sorry for asking here but the forum presents a blank page after I click the button to make a new post)

The demo seems to be able to get the info I'm interested (duration of the audio):
![image](https://user-images.githubusercontent.com/1757768/61999607-47b71880-b0bd-11e9-8e97-73916e2e63e2.png)

But in my own code, I get this error:

> Fatal error: Uncaught Error: Class 'getid3_handler' not found in /opt/lampp/htdocs/getid3/module.audio.mp3.php:25 Stack trace: #0 /opt/lampp/htdocs/baile.php(3): include() #1 {main} thrown in /opt/lampp/htdocs/getid3/module.audio.mp3.php on line 25

For this PHP code:
```
include "getid3/getid3.lib.php";
include "getid3/module.audio.mp3.php";
include "getid3/module.tag.id3v1.php";
include "getid3/module.tag.apetag.php";
include "getid3/module.tag.id3v2.php";

$pathName = "https://path-to-my.mp3";
$getID3 = new getID3; 
$ThisFileInfo = $getID3->analyze($pathName);
$len= @$ThisFileInfo['playtime_string']; // playtime in minutes:seconds, formatted string
echo "Length of mp3 is " + $len;

```
Can you tell me where I'm going wrong with getid3_handler? The version in the change log is 1.9.17: [2019-02-07] James Heinrich :: 1.9.17-201902071234

PHP v7.3.6

**Comment by tenleftfingers** [comment]
It's been solved by replacing my includes with the "require_once('getid3/getid3.php');" in the demo file. Apologies.

**Comment by JamesHeinrich** [comment]
Thanks for reporting the forum issue, should be fixed now.
