### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by jrfnl** [JamesHeinrich/getID3#200]
Any chance of a new release in the near future ? Would be great for external projects, like WordPress which includes GetID3 as a dependency, to be able to upgrade to a new tagged release before PHP 7.4 comes out.

**Comment by BrookeDot** [comment]
Having 2.0 officially tagged would  also help with problems like this https://github.com/phanan/koel/issues/1078

**Comment by JamesHeinrich** [comment]
v1.9.18 tagged (unchanged from 1.9.17-201907240906 except for version and changelog)

**Comment by jrfnl** [comment]
Thank you! Appreciated.
