### ISSUE TITLE
Cover encodage forma

### ISSUE THREAD

**Issue by Nathan-Al** [JamesHeinrich/getID3#202]
Hello,
I don't knpow if that the right place to write but well, i try to use your code for a personal project (good jobs between) and i need to use the song cover but i don't know witch format the image is.
So if you can tell me that really help me, thank in advance  !

Good days.

**Comment by JamesHeinrich** [comment]
It's unclear if you're trying to read or write the cover image, and what tag format you're dealing with.

In general, you should be able to use pretty much any format for attached images. As it says on the [ID3v2.3 specs](http://id3.org/id3v2.3.0#Attached_picture):
> The "image/png" or "image/jpeg" picture format should be used when interoperability is wanted.

**Comment by Nathan-Al** [comment]
Hello,

Sorry if i'm no very clear my english is kind of bad.
When i try to use : [comments][picture][0][data] 
there a bunch of weird charachters that appear, i know for experience that means the image is enconded but i don't know what encondage is. I want to chow the picture so read it i guess.
If i need to register the image before tell me please and how if you can.
Thank in advance.

**Comment by JamesHeinrich** [comment]
Look at the rest of `[comments][picture][0]`, specifically `[comments][picture][0][image_mime]`

If you're not sure what data is available where, please open /demo/demo.browse.php in your browser  and browse to the file you want to analyze to see a more graphical representation of the returned data.

As a rough guide, GIF files start with "GIF", PNG files start with "%PNG", and JPEG files start with something like `ÿØÿà`

**Comment by Nathan-Al** [comment]
Ok now i understand thank you to clarify ! Can ask something ? Why your team create all the code in one page ? Not a critic just a question.

**Comment by JamesHeinrich** [comment]
Not sure what you mean by "all in one page"?
getID3() consists of about 75 different source files.

**Comment by Nathan-Al** [comment]
The demo, the two part, and all of the part that explain what you can do.
