### ISSUE TITLE
Multiple id3v2 artists are not copied when using CopyTagsToComments()

### ISSUE THREAD

**Issue by blakyris** [JamesHeinrich/getID3#206]
Most of the time for me files read by getID3() shows multiple artists in an array when they are stored in a ID3v2 format but just the first artist is copied when using `CopyTagsToComments()` so I have to extract my self which is VERY anoying because I have to handle all tags format myself.

**Comment by JamesHeinrich** [comment]
Can you please provide a sample file with multiple artists to ease my testing?

**Comment by blakyris** [comment]
Yes sure !
The file was encoded from FLAC to MP3 using MusicBee. In the FLAC format tags are correctly read.

![console-tags](https://user-images.githubusercontent.com/10896518/69647799-6aa50980-106a-11ea-92d7-54cbb7342e3f.png)
![windows-tags](https://user-images.githubusercontent.com/10896518/69647801-6aa50980-106a-11ea-88be-e7ac57f3dd3e.png)
[track.zip](https://github.com/JamesHeinrich/getID3/files/3892598/track.zip)

**Comment by JamesHeinrich** [comment]
One missing character inverted the logic. Thanks for the sample file, it made testing and fixing easy.
Fixed in https://github.com/JamesHeinrich/getID3/commit/96430a14ff4a728160b056d1268dac402c8e6401

**Comment by blakyris** [comment]
Thanks !!! That will make my life easier
