### ISSUE TITLE
Getting data from an embed video

### ISSUE THREAD

**Issue by Wish-sher** [JamesHeinrich/getID3#212]
Hey,
I was wondering that if I had an embed video URL from google drive or something, can I get that video meta data like duration or size from it?
If I can, please tell me.

**Comment by JamesHeinrich** [comment]
If you can figure the part out to grab at least the first portion (100kB or so should be fine) of the file from whichever remote location, then yes. getID3 only makes an effort to work on local files, it's left to the user to handle fetching any remote data.
