### ISSUE TITLE
Function get_magic_quotes_runtime() is deprecated

### ISSUE THREAD

**Issue by Farhad-Ghasemi** [JamesHeinrich/getID3#213]
Hi, there is an issue while upgrading to php 7.4 in getid3.php line 299.
Please fix this issue and create a tag.

**Comment by JamesHeinrich** [comment]
I don't believe you're using the current version. The [current code](https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L299-L313) was already changed for PHP v7.4 more than 2 weeks ago in https://github.com/JamesHeinrich/getID3/commit/75454e8b19c7b1b041382b91906574fe484f605b
