### ISSUE TITLE
Support Writing Rating Tag for Display in Explorer / Windows Media Player

### ISSUE THREAD

**Issue by Calliostro** [JamesHeinrich/getID3#216]
Hello James Heinrich,

I want to suggest to remove the check for a valid email address in **write.id3v2.php:910**

This way it is possible to write the rating tag which is displayed in Explorer and Windows Media Player. They use the value "Windows Media Player 9 Series" for email field (see https://en.wikipedia.org/wiki/ID3#ID3v2_rating_tag_issue)

For testing change in **demo.simple.write.php:48** from:
`'popularimeter' => array('email'=>'user@example.net', 'rating'=>128, 'data'=>0),`

to:
`'popularimeter' => array('email'=>'Windows Media Player 9 Series', 'rating'=>128, 'data'=>0),`

In current version you get the error message that email is not correct.

But this is the way to get the stars displayed in Explorer and Windows Media Player.

Kind regards
Denis

**Comment by JamesHeinrich** [comment]
Changed from Error to Warning in https://github.com/JamesHeinrich/getID3/commit/47135281d930d49859a8816a203347d8730c0474
