### ISSUE TITLE
CopyTagsToComments doesn't copy "covr" picture from quicktime/mp4/m4a

### ISSUE THREAD

**Issue by ben-xo** [JamesHeinrich/getID3#218]
the quicktime atom for cover art is "covr", but I had to dig deeper to extract images - CopyTagsToComments works just fine for MP3 embedded artwork, however.

See https://github.com/ben-xo/dir2cast/commit/5bf361616a3da15e623d9105d7ef434d1d7d6480 for how I worked around the issue in my app (recursive search for 'covr' atom)

**Comment by JamesHeinrich** [comment]
getID3 by convention is supposed to copy attached images to the [<tagtype>][comments][picture] key, and then getid3:HandleAllTags will _move_ (to save memory, avoid reduplicating large data) the pictures from the tag-specific comment section to the global [comments] section:
https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L1454-L1456
https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L1482-L1524

module.audio-video.quicktime wasn't doing that for _covr_ atoms, it does now: https://github.com/JamesHeinrich/getID3/commit/c37956c260ac31b37b740ba6ec587f48f65248c0
