### ISSUE TITLE
CopyTagsToComments() always creates HTML versions of the tags even if option_tags_html=false

### ISSUE THREAD

**Issue by ben-xo** [JamesHeinrich/getID3#221]
I have submitted https://github.com/JamesHeinrich/getID3/pull/220 to address this.

**Comment by ben-xo** [comment]
This patch doesn't address the problem that CopyTagsToComments() re-html-izes every comment it copies, even if the tags array already had an html-ized version, meaning that some work is done twice.

**Comment by JamesHeinrich** [comment]
Thanks, merged.

Feel free, if you're so inspired, to submit more fixes to fix the rest of the problem as you described.
