### ISSUE TITLE
Typo for genre name and extension of the exception list for genre parser

### ISSUE THREAD

**Issue by Calliostro** [JamesHeinrich/getID3#223]
Hi James Heinrich,

In **module.tag.id3v2.php:526** this is a typo, isn't it? You are searching for the genre "Rock/Rock", but I think you meant "Folk/Rock".

Could this list of exceptions be made configurable? If I want to use the tags from Discogs, I would have to add "RnB/Swing" and "Funk / Soul" (with spaces) to the list.

https://www.discogs.com/en/genre/funk+%2F+soul
https://www.discogs.com/en/style/rnb%2Fswing

Many greetings
Denis

**Comment by JamesHeinrich** [comment]
Yes, "Rock/Rock" would be a typo. But actually in looking up the references, "Folk-Rock" is the proper version with a hyphen not a slash, so it shouldn't be part of this list anyways.

I have [changed](https://github.com/JamesHeinrich/getID3/commit/c6d53130f8addfdaf669101f229da9ba1b73d632) the code section slightly by putting the list of exceptions in an array that's easily extended (and should help avoid typos like "Rock/Rock"), and added in the three slashed examples I found from Discogs

**Comment by Calliostro** [comment]
Many thanks for the quick solution!
