### ISSUE TITLE
Could not open S3 URL + hight and width is null

### ISSUE THREAD

**Issue by xpertyst** [JamesHeinrich/getID3#234]
Not able to get AWS S3 video height and width. 
Array ( [GETID3_VERSION] => 1.9.19-202003041359 [error] => Array ( [0] => Could not open "https:\\............-bucket.s3.amazonaws.com\somefile_name.mp4" (!is_readable; !is_file) ) )

**Comment by JamesHeinrich** [comment]
getID3 works on local files. It's your responsibility to get a copy of the remote file locally for analysis, although depending on the file in question you may be able to get away with just copying a portion of the file (from 10kB to 10MB, depending on what kind of file and what's in it).

https://github.com/JamesHeinrich/getID3/blob/master/readme.txt#L174-L206
