### ISSUE TITLE
Uncaught error: Class 'getid3_handler'

### ISSUE THREAD

**Issue by jim-moe** [JamesHeinrich/getID3#239]
Regularly found in "error_log":
`[03-Apr-2020 09:32:17 UTC] PHP Fatal error:  Uncaught Error: Class 'getid3_handler' not found in /.../wp-includes/ID3/module.audio.ac3.php:18
Stack trace:
#0 {main}
  thrown in /.../wp-includes/ID3/module.audio.ac3.php on line 18`

getid3 version: 1.9.18-201907240906

**Comment by JamesHeinrich** [comment]
Related to https://github.com/JamesHeinrich/getID3/pull/236 and should not happen with the current version (1.9.19-202003111819). If you still experience this error after updating to that version (or newer) then please reopen this issue.
