### ISSUE TITLE
this library not working in big video file

### ISSUE THREAD

**Issue by Mr-Kiany** [JamesHeinrich/getID3#240]
when upload video size more than 300MB it's not calculate video duration

**Comment by JamesHeinrich** [comment]
You'll need to provide more details. What format of video file are you analyzing? What output (especailly warnings and error messages) does getID3 return when analyzing your file?

There is no particular size limit on files analyzed by getID3, although some formats are dependent on knowing the entire filesize (may be a problem for >2GB files on 32-bit PHP installations), but 300MB would be considered "small" for a video file.

**Comment by Mr-Kiany** [comment]
@JamesHeinrich 
this is my code
`
$temp_file = $_FILES['file']['tmp_name'];
$getID3 = new getID3;
    $file = $getID3->analyze($temp_file);
    $time = $file['playtime_string'];
`

**Comment by JamesHeinrich** [comment]
Sure. That doesn't answer my questions though. What file format? What do you get from `var_dump($file['warning']);` and/or `var_dump($file['error']);` ?

**Comment by JamesHeinrich** [comment]
No response from original poster after 14 days, marking issue as closed.
