### ISSUE TITLE
Use this library for analysis content of audio and set metadata?

### ISSUE THREAD

**Issue by Camelia2020** [JamesHeinrich/getID3#241]
I was looking for a sound analysis library that I came across. I need to use it in a php program.
Can this library get a audio as input and then analysis its and identify audio subjects and send them as output? Subjects are important content for audio content.
Or can subjects be assigned to one voice as metadata? for example set some subject with start time in audio tags. 

I want to put an audio file on the web. I want to identify the topics that have been discussed, such as books, sports, etc., and tag them on the audio. Search by tag to identify the sound with the start time of the searched topic.
Can I use this library for this purpose?

**Comment by JamesHeinrich** [comment]
I'm not sure I fully understand your question, but yes, getID3 is used to get metadata from audio and video files, both intrinsic (format, bitrate, length, etc) and explicitly-stored data (title, artist, album, genre, etc). See the demos for examples of what data is returned by getID3,  like [this](https://www.getid3.org/demo/Lyrics3.mp3.html).

getID3 can also write a limited number of metadata formats, but writing support is very crude and limited compared to reading support.
