### ISSUE TITLE
writing tags for .flac-files

### ISSUE THREAD

**Issue by UblerUnhold** [JamesHeinrich/getID3#245]
Hello,

now, I am not much of a programmer, and I don't know much about ID3 either, so I might miss something very obvious.

I am using the the code that I found here:

https://www.getid3.org/phpBB3/viewtopic.php?t=284

and I try to write the tags to a .flac file. I only modified the path to the audio file and I get these errors:

`Failed to write tags!
Tag format "id3v1" is not allowed on "flac.flac" files`

and

`Notice: Undefined variable: TaggingFormat in C:\wamp64\www\Audio\index.php on line 6`

Line 6 is

`$getID3->encoding = $TaggingFormat;`

If it should be relevant, I am using PHP version 7.3.12

Is it even possible to write .flac-tags? getID3 reads them fine (demo.browse.php).

Thanks for any help.

**Comment by JamesHeinrich** [comment]
FLAC files should only be tagged with FLAC comments, not ID3.
See [demo.simple.write.php](https://github.com/JamesHeinrich/getID3/blob/master/demos/demo.simple.write.php) except you would want 
`$tagwriter->tagformats = array('metaflac');`

All the FLAC tag writing is handled natively by the official [metaflac](https://xiph.org/flac/documentation_tools_metaflac.html) program, not really getID3 itself, so you need to have it available on your system (you will need to [download](https://xiph.org/flac/download.html) & install it if you don't already have it).

**Comment by UblerUnhold** [comment]
Thank you James, it works!
 

Gesendet: Samstag, 25. April 2020 um 03:15 Uhr
Von: "James Heinrich" <notifications@github.com>
An: "JamesHeinrich/getID3" <getID3@noreply.github.com>
Cc: "UblerUnhold" <tosentier@gmx.li>, "Author" <author@noreply.github.com>
Betreff: Re: [JamesHeinrich/getID3] writing tags for .flac-files (#245)


 

FLAC files should only be tagged with FLAC comments, not ID3.
See demo.simple.write.php except you would want
$tagwriter->tagformats = array('metaflac');

All the FLAC tag writing is handled natively by the official metaflac program, not really getID3 itself, so you need to have it available on your system (you will need to download & install it if you don't already have it).
