### ISSUE TITLE
Incorrect Data

### ISSUE THREAD

**Issue by picard102** [JamesHeinrich/getID3#246]
Not sure if it's the file, or something I'm doing, but whenever I try to get the meta data for this file (https://traffic.megaphone.fm/MTS3628971830.mp3) I get this:

file_length: 124.093125
file_size: null
mime_type: "audio/mpeg"
status: 200
type: "audio"

The file size and length are incorrect.

**Comment by JamesHeinrich** [comment]
getID3 does not analyze remote files. If the filesize is incorrect then whatever you're doing to get the remote file is not getting the entire file. And if the file you're analyzing is truncated, it's not surprising the calculated duration is also incorrect.
