### ISSUE TITLE
getid3_lib::array_min finds max instead of min

### ISSUE THREAD

**Issue by quasilyte** [JamesHeinrich/getID3#247]
https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.lib.php#L707

Both `getid3_lib::array_min` and `getid3_lib::array_max` seem to find array max.

This might be a copy/paste mistake. I assume `array_max` was copied, variables were renamed, but the condition was not changed.

```php
	/**
	 * @param array $arraydata
	 * @param bool  $returnkey
	 *
	 * @return int|false
	 */
	public static function array_max($arraydata, $returnkey=false) {
		$maxvalue = false;
		$maxkey = false;
		foreach ($arraydata as $key => $value) {
			if (!is_array($value)) {
				if ($value > $maxvalue) {
					$maxvalue = $value;
					$maxkey = $key;
				}
			}
		}
		return ($returnkey ? $maxkey : $maxvalue);
	}

	/**
	 * @param array $arraydata
	 * @param bool  $returnkey
	 *
	 * @return int|false
	 */
	public static function array_min($arraydata, $returnkey=false) {
		$minvalue = false;
		$minkey = false;
		foreach ($arraydata as $key => $value) {
			if (!is_array($value)) {
				if ($value > $minvalue) {
					$minvalue = $value;
					$minkey = $key;
				}
			}
		}
		return ($returnkey ? $minkey : $minvalue);
}
```
Note that it's not enough to change `>` to `<`. The initial value of `minvalue` needs to be changed too, otherwise `array_min` could return `false`.

**Comment by JamesHeinrich** [comment]
Thanks, fixed in https://github.com/JamesHeinrich/getID3/commit/13dc22a248610631c355a22725aa685f97a7d68a
