### ISSUE TITLE
.TS doesn't support

### ISSUE THREAD

**Issue by jhemmmm** [JamesHeinrich/getID3#265]
Hello,

If possible, can you add a support for .ts files?.

**Comment by jhemmmm** [comment]
![image](https://user-images.githubusercontent.com/14343151/92257968-abd71d80-ef08-11ea-9fd9-c17e50700259.png)

**Comment by JamesHeinrich** [comment]
If it were easily possible, I would have done so years ago.  If somebody wants to write a module to add proper .ts support I'll be happy to include it.
