### ISSUE TITLE
Any chance of future development to include guan chunks in parsing of RIFF/WAVE?

### ISSUE THREAD

**Issue by helenchappell** [JamesHeinrich/getID3#267]
These are used in some audio recorders such as Wildlife Acoustics Songmeters, used for recording birdsong and bats:
https://github.com/riggsd/guano-spec/blob/master/guano_specification.md#guano---grand-unified-acoustic-notation-ontology
https://www.wildlifeacoustics.com/SCHEMA/GUANO.html
I am loading such files on citizen science website www.naturesaudio.org and trying to get the original recording time from the meta data, programmatically.
Thanks, Helen

**Comment by JamesHeinrich** [comment]
Do you have a sample file that I can look at?

**Comment by helenchappell** [comment]
Here's a link to a file recorded on SM4-BAT:
https://1drv.ms/u/s!AnNIeeStm9NOjFbH5354JsM5gfam

**Comment by helenchappell** [comment]
I'm looking at the file myself just now.  Think the data may be found in the wamd chunk.  Found this Python library https://guano-py.readthedocs.io/en/latest/index.html  which I hope will help :)

**Comment by JamesHeinrich** [comment]
WAMD = Wildlife Acoustics MetaData which seems to be a semi-proprietary format used by WildlifeAccoustics sounds recorders (or so I've read), stored in `wamd` chunk. But it's distinct and separate from GUANO (which seems to have nice documentation) whereas WAMD doesn't seem to have much (if any?) documentation.

Looking at the sample file you linked I can see timestamp, GPS coordinates, possibly temperature(?) but from a single sample file and no documentation I could but guess as to the actual structure.

If you can provide a sample file with GUANO data in a `guan` chunk I can look at that.

**Comment by helenchappell** [comment]
Thanks I'll have to get back to the Wildlife Acoustics people as they told me they used guan but we don't see it in that file, which was recorded on one of their devices.  I'm having the same problem with lack of documentation for wamd.
Really appreciate you taking the time to look, will post an update when I get their response.
Learning more than I expected about parsing audio files for meta data :)

**Comment by helenchappell** [comment]
For completion, here's a link to a file with a guan chunk: https://1drv.ms/u/s!AnNIeeStm9NOjFd5A1wNB_bjrVsj?e=VggNDX
I am using getID3 then parsing the guan chunk data string.  Example (from print_r) is : 

Guan chunk: Array
(
    [0] => Array
        (
            [offset] => 14400512
            [size] => 360
            [data] => GUANO|Version:1.0
Firmware Version:1.1
Make:Wildlife Acoustics, Inc.
Model:Song Meter Mini
Serial:SMA00646
WA|Song Meter|Prefix:SMA00646
WA|Song Meter|Audio settings:[{"rate":24000,"gain":18}]
Length:300.000
Original Filename:SMA00646_20201017_130500.wav
Timestamp:2020-10-17 13:05:00+1:00
Loc Position:54.75656 -1.59106
Temperature Int:21.25
Samplerate:24000

        )

)

Thanks,
Helen

**Comment by JamesHeinrich** [comment]
Thanks for the sample file. `RIFF.guan` comments are now parsed into `$info['riff']['guano']`
https://github.com/JamesHeinrich/getID3/commit/a45d2b58aba1b2432f582e5c3791f2a5dbb1dd27

**Comment by helenchappell** [comment]
Fab thanks
