### ISSUE TITLE
Remote file mp3 problem

### ISSUE THREAD

**Issue by romanoh** [JamesHeinrich/getID3#269]
Please, i use this code to get an remote mp3:

```
// Copy remote file locally to scan with getID3()
require_once('../getid3/getid3.php');
$remotefilename = 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3';
if ($fp_remote = fopen($remotefilename, 'rb')) {
	$localtempfilename = tempnam('/tmp', 'getID3');
	if ($fp_local = fopen($localtempfilename, 'wb')) {
		while ($buffer = fread($fp_remote, 32768)) {
			fwrite($fp_local, $buffer);
		}
		fclose($fp_local);
		$remote_headers = array_change_key_case(get_headers($remotefilename, 1), CASE_LOWER);
		$remote_filesize = (isset($remote_headers['content-length']) ? (is_array($remote_headers['content-length']) ? $remote_headers['content-length'][count($remote_headers['content-length']) - 1] : $remote_headers['content-length']) : null);
		
		// Initialize getID3 engine
		$getID3 = new getID3;
		
		$ThisFileInfo = $getID3->analyze($localtempfilename, $remote_filesize, basename($remotefilename));
		
		// Delete temporary file
		unlink($localtempfilename);
	}
	fclose($fp_remote);
}

```
but the page is blank, what i am doing wrong? no error is given.

**Comment by JamesHeinrich** [comment]
Your code analyzes the file, but doesn't do anything with the information.

You'll probably want to put `$getID3->CopyTagsToComments($ThisFileInfo);` after the call to analyze, and then output something, even just `print_r($ThisFileInfo);` will get you started (or `echo '<pre>'.htmlentities(print_r($ThisFileInfo, true), ENT_SUBSTITUTE).'</pre>';` if you're outputting to HTML).

If there are actual errors or warnings they will appear in

**Comment by romanoh** [comment]
Thank you it work very nice!
but i cannot use my synology web station link: 
`Warning: fopen(http://192.168.1.76/03%20-%20Lavender%20(2017%20Remaster).mp3): failed to open stream: Connection timed out in /home/morrisseyradio/public_html/getid3/demos/fora do site.php on line 12`

is there any issue for synology or am i doing something wrong? please

**Comment by JamesHeinrich** [comment]
That's a pure PHP issue, nothing to do with getID3. If you can open that URL with your browser but not over PHP then there may be some Synology-specific issue I'm unfamiliar with.
