### ISSUE TITLE
Why are some ID3v2 frames not added to [tags][id3v2]?

### ISSUE THREAD

**Issue by nickrobillard** [JamesHeinrich/getID3#271]
Hi. I recently noticed that **UFID (unique_file_identifier)** frame data isn't being added to `['tags']['id3v2']`. Upon closer inspection, I see that several other frames are also not included here. What is the logic behind which data is added to `['tags']['id3v2']` and which data is not?

After looking through the code, I see that `['tags']['id3v2']` is built up by iterating over `['id3v2']['comments']`. So if a tag isn't included in `['id3v2']['comments']`, it won't be included in `['tags']['id3v2']`. We can see this in `src/Module/Tag/ID3v2.php ParseID3v2Frame`. There is special handling for several types of frames and I can see that many of them add their data to `['id3v2']['comments']` but many do not - like UFID, ETCO, MLLT, SYTC, SYLT, RVA2, RVAD (and several more).

If I had to guess why this - I would think that it has to do with the complexity or non-standard nature of the data within these frames. However, if this is the case, I would posit that some frames aren't _that_ complex. UFID frames, for example, each have an **ownerid** string and a **data** string. Anyways, any insight into this would be greatly appreciated!

(Related to #182)

**Comment by JamesHeinrich** [comment]
[id3v2][comments] is populated with contents of common frames such as artist, title, album, genre, etc. Certainly there are any number of other frames that a particular user _might_ be interested in, but I didn't consider them common enough to include in the [comments] section. As always, all frame data can be found in the raw [id3v2][<frameID>] data.

If you think that one (or more) ID3v2 frames would be significant candidates for inclusion in [comments] please suggest them, with examples of the type of data they might contain, and a brief reason for inclusion, and I'll consider including them.

**Comment by nickrobillard** [comment]
Got it - that makes sense. Is there a complete list of some sort that I can reference (in code or documentation) of these common frames? I've started going through the conditions in `ParseID3v2Frame` and identifying the ones that don't add to [comments] but as you can imagine, it's a bit time consuming. Apologies if I missed it somewhere.

**Comment by JamesHeinrich** [comment]
There's no specific documentation, you can slog through the code exactly as you've been doing and make notes. It's perhaps easier to document the ones that _do_ add to [comments] and then it's safe to assume that any not in that list do not. If you do compile a list of frames that get copied to [comments] perhaps you can post it here so there's some documentation for the next user :)

**Comment by nickrobillard** [comment]
I have gone through our list of id3v2 tags and confirmed the tags that end up under [tags][id3v2]. Note that I did this within the context of an external project and our list may have been incomplete. So it is possible that I missed some. But feel free to reference my findings here https://github.com/AzuraCast/AzuraCast/issues/3232#issuecomment-706767815. I will close this issue now. @JamesHeinrich thank you for your input!
