### ISSUE TITLE
Can't read chapters data in ID3 v2.4

### ISSUE THREAD

**Issue by SebastienBoisard** [JamesHeinrich/getID3#279]
Hello,

I've been working with getID3 and it's working great :+1: except with chapter data in ID3 v2.4.

I tried with getID3-1.9.20 to read the chapter data of the same MP3 file written in ID3 v2.3 and ID3 v2.4 (with eyeD3, files here :
[test_one_chapter_ID3_v2.zip](https://github.com/JamesHeinrich/getID3/files/5695264/test_one_chapter_ID3_v2.zip) ) with this code: 

```
<?php

require_once('../getid3/getid3.php');

$id3 = (new \getID3())->analyze('test_one_chapter_ID3_v2_3.mp3')['id3v2']['chapters'];
print("\nID3 v2.3 chapter data:\n");
var_dump($id3);

$id3 = (new \getID3())->analyze('test_one_chapter_ID3_v2_4.mp3')['id3v2']['chapters'];
print("\nID3 v2.4 chapter data:\n");
var_dump($id3);
```

And as a result, data in the ID3 v2.4 are missing:

```
ID3 v2.3 chapter data:
array(1) {
  [0]=>
  array(5) {
    ["time_begin"] => int(2000)
    ["time_end"] => int(3000)
    ["chapter_name" ] => string(13) "my only title"
    ["chapter_url"] =>
    array(1) {
      ["chapter url"] => string(23) "https://www.google.com/"
    }
    ["picture_present"] => bool(true)
  }
}

ID3 v2.4 chapter data:
array(1) {
  [0]=>
  array(2) {
    ["time_begin"] => int(2000)
    ["time_end"] => int(3000)
  }
}
```
Any hints would be appreciated on this problem.
Thanks a lot for all the work you've done.

**Comment by JamesHeinrich** [comment]
If you look at the `warnings` for the ID3v2.4 version you see: `CHAP subframe "APIC" at frame offset 29 claims to be "751878" bytes, which is more than the available data (195788 bytes)`
However, the JPEG image that is there is indeed only 195700 bytes long.
The `APIC` subframe length is written in the file (offset 43..46) as `00 0B 79 06` which is the 751878 value, but the correct value should be 195718 `00 02 FC 86`. If I edit those 3 bytes to match the correct length then the file parses fine. See [edited sample](https://github.com/JamesHeinrich/getID3/files/5698826/_.git279.-.test_one_chapter_ID3_v2_4-edit.zip).

I would assume this is a bug in the program that wrote the tag, perhaps check with that developer?
I'll close this ticket for now, if you have additional evidence pointing towards it being a getID3 but please reopen it.
