### ISSUE TITLE
Very slow parsing of wavpack file

### ISSUE THREAD

**Issue by Globulopolis** [JamesHeinrich/getID3#296]
Hi!
I'm trying to parse `.wv` file but it very slow. It took almost 2min to parse. How can I speed up this process?

**Comment by JamesHeinrich** [comment]
Can you please provide a sample file that shows this slow behaviour? Either post here or to info@getid3.org

**Comment by JamesHeinrich** [comment]
Testing locally (on HDD not SSD) your testfile parsed for me in 1.795 seconds.

**Comment by Globulopolis** [comment]
I try to parse other wavpack file and it took 3sec to parse via slow network. File 300Mb size. Very strange...

**Comment by JamesHeinrich** [comment]
I added a `quick_parsing` option to getid3_wavpack which avoids scanning all the blocks in the file (it breaks the loop once it's found riff_header and config_block blocks). This changes the parsing time on my test system from 1.8s to 0.02s
https://github.com/JamesHeinrich/getID3/commit/a9fa1bbd4f60de516150473603b6057f7b9ce3e0

**Comment by Globulopolis** [comment]
@JamesHeinrich any piece of code how to set this option?

My code:
$getID3 = new getID3;
$getID3->setOption(array('quick_parsing' => true));
$data = $getID3->analyze($filepath);

Does nothing. It scan with the same result.
