### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: decbin(): Argument #1 ($num) must be of type int, string given

### ISSUE THREAD

**Issue by calliostro** [JamesHeinrich/getID3#299]
Hello James Heinrich

Recently I get more and more often the error when reading files:

> PHP Fatal error:  Uncaught TypeError: decbin(): Argument #1 ($num) must be of type int, string given

Not to exclude that the MP3 files are not quite correct from the structure, on the other hand MP3 Diags can not find errors.

I help myself with additional check in the function `\getid3_lib::Dec2Bin($number)` whether the parameter really contains a number and get out otherwise.

**getid3.lib.php:429**
```php
public static function Dec2Bin($number) {
    if (!is_numeric($number)) {
        trigger_error('TypeError: Dec2Bin(): Argument #1 ($number) must be numeric, '.gettype($number).' given', E_USER_WARNING);
        return '';
    }
    :
    :
}
```

Does it make sense to apply this change?

Many greetings
Joey

**Comment by JamesHeinrich** [comment]
I would be more comfortable seeing a sample file that exhibits this problem first, to see how or where it's being called inappropriately.

**Comment by JamesHeinrich** [comment]
I took a look at your sample file but didn't notice any such warnings. What version of PHP are you using?

**Comment by Calliostro** [comment]
Good tip, the error comes under PHP 8.0.3.

I just tried it with PHP 7.4.11, there it runs without problems.

That explains then why I have only been observing this for some time. I have not brought it in connection with the switch to PHP 8.

**Comment by paulijar** [comment]
This issue seems to be the root cause of the issue https://github.com/owncloud/music/issues/867. There, we can find also a stack trace showing that the bad call to `Dec2Bin` comes from here: https://github.com/JamesHeinrich/getID3/blob/acf86e01dbebbd6be0e2c043b9c5c97e71aea5d6/getid3/module.tag.id3v2.php#L1965

This line of code is obviously passing in a string while `Dec2Bin` expects to get an int. Older PHP versions probably apply an implicit type conversion when this string gets passed to `decbin` but PHP8 is more strict.

**Comment by JamesHeinrich** [comment]
Please reopen this issue if https://github.com/JamesHeinrich/getID3/commit/4e5bcaf39eaa033e21e722c8788dcaa3d71c8b3a doesn't fix your problem.

**Comment by JamesHeinrich** [comment]
I just came across a sample MP3 file that exhibited this problem, related to code parsing the RGAD (replay gain) tag improperly. I have rewritten that section of the code in https://github.com/JamesHeinrich/getID3/commit/0bc9aca9bb7fda128511cc2c038d7bab178cbc37.
