### ISSUE TITLE
Remove support for deprecated/removed php features

### ISSUE THREAD

**Issue by duncan3dc** [JamesHeinrich/getID3#30]
The minimum php version we will support is 5.4, so anything that was removed by then should not be used/considered inside getID3.

We should also look to avoid any deprecated features, the obvious one is the mysql cache which uses the mysql_ functions, but there are a few others. We could provide an interface to allow developers to create their own cache handlers

This will likely need multiple issues to follow once we've identified all the features that need updating

**Comment by soulhunter1987** [comment]
I removed some old code from base getid3.php, but it is hard to identify all outdated features visually. I think the best way to do this is to set up our demo/test repo according to #34 and launch demo on all available test files with PHP 5.4 and E_DEPRECATED flag switched on. It will then output all problems.

**Comment by duncan3dc** [comment]
* Removed magic_quotes in fa96e0d9bef67583130e96bae203aad9ed7bce75
* Removed save_mode in 91677a280304c260e3084a6d26196eab9228da13
