### ISSUE TITLE
PHPCompatibility test 

### ISSUE THREAD

**Issue by Equipement** [JamesHeinrich/getID3#300]
Hello,

I have run a test with PHPCompatibility (for PHP Code Sniffer).
Here's the result of the test :

FILE: D:\getid3\getid3.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 6 WARNINGS AFFECTING 6 LINES
----------------------------------------------------------------------
  425 | WARNING | INI directive 'safe_mode' is deprecated since PHP
      |         | 5.3 and removed since PHP 5.4
  429 | WARNING | INI directive 'mbstring.func_overload' is
      |         | deprecated since PHP 7.2
  433 | WARNING | INI directive 'mbstring.func_overload' is
      |         | deprecated since PHP 7.2
  440 | WARNING | Function get_magic_quotes_runtime() is deprecated
      |         | since PHP 7.4
  446 | WARNING | Function get_magic_quotes_gpc() is deprecated since
      |         | PHP 7.4
 1768 | WARNING | INI directive 'safe_mode' is deprecated since PHP
      |         | 5.3 and removed since PHP 5.4
----------------------------------------------------------------------

FILE: D:\getid3\module.audio-video.quicktime.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 141 | ERROR | list() will assign variable from left-to-right since
     |       | PHP 7.0. Ensure all variables in list() are unique to
     |       | prevent unexpected results.
----------------------------------------------------------------------

FILE: D:\getid3\module.audio.shorten.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 121 | WARNING | INI directive 'safe_mode' is deprecated since PHP
     |         | 5.3 and removed since PHP 5.4
----------------------------------------------------------------------

FILE: D:\getid3\write.metaflac.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
  54 | WARNING | INI directive 'safe_mode' is deprecated since PHP
     |         | 5.3 and removed since PHP 5.4
 166 | WARNING | INI directive 'safe_mode' is deprecated since PHP
     |         | 5.3 and removed since PHP 5.4
----------------------------------------------------------------------

FILE: D:\getid3\write.vorbiscomment.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 53 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3
    |         | and removed since PHP 5.4
----------------------------------------------------------------------

FILE: D:\getid3\extension.cache.mysql.php
----------------------------------------------------------------------
FOUND 27 ERRORS AFFECTING 25 LINES
----------------------------------------------------------------------
 112 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 118 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 131 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 132 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 136 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 137 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 153 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 153 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 154 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 154 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 180 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 181 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 182 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 183 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 184 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 185 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 187 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 197 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 198 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 199 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 200 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 201 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 202 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 203 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 217 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 224 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
 225 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and
     |       | removed since PHP 7.0; Use mysqli instead
----------------------------------------------------------------------

**Comment by StudioMaX** [comment]
This code is indeed present due to the compatibility layer with older PHP versions. If you look in more detail, next to every deprecated function there is a check that this function can actually be used within the current PHP version. Have you found any real execution problems with these deprecated functions/INI directives?

**Comment by Equipement** [comment]
Hello, thank you for this information.
Does it mean that getid3 is compatible with PHP 7.4 ?
I haven't found any real execution problems.

**Comment by StudioMaX** [comment]
Yes, getID3 v1.9 must be compatible with PHP from 5.3 and up to 8.1-beta. Some of these deprecated checks have been removed in getID3 v2.0-beta, but it should be used only through Composer.

**Comment by QuixThe2nd** [comment]
Should this issue be closed? It's been a year.
