### ISSUE TITLE
ID3 Tag version

### ISSUE THREAD

**Issue by mpgradio** [JamesHeinrich/getID3#301]
I am using a meta.html and meta.php to list mp3 information.
as the below..in meta.php I have tried all the below to echo the current mp3 tag version. (such as id3v1 or id3v2.3)
```
$sList .= '<tr>';
$sList .= '<td>'.$aTags['Title'].'</td>';
//$sList .= '<td>'.$aTags['Author'].'</td>';
//$sList .= '<td>'.$aTags['Album'].'</td>';
//$sList .= '<td>'.$aTags['Composer'].'</td>';
//$sList .= '<td>'.$aTags['AlbumAuthor'].'</td>';
//$sList .= '<td>'.$aTags['Genre'].'</td>';
$sList .= '<td>'.$aTags['Artist'].'</td>';
$sList .= '<td>'.$aHeaders['bitRate'].'</td>';
$sList .= '<td>'.$aHeaders['sampleRate'].'</td>';

//$sList .= '<td>'.$fileinfo['tags'].'</td>'; // cannot seem to get this part to display the tag version information.
//$sList .= '<td>'.$aHeaders['tags'].'</td>'; // cannot seem to get this part to display the tag version information.
//$sList .= '<td>'.$aTags['tags'].'</td>'; // cannot seem to get this part to display the tag version information.
//$sList .= '<td>'.$aTags['tag'].'</td>'; // cannot seem to get this part to display the tag version information	

$sList .= '<td><a href="edittags.php?Filename='.urlencode($sSingleFile).'"><button class="button"><font color="white"> Edit Tags</font></button></a></td>';
$sList .= '</tr>';
```

**Comment by JamesHeinrich** [comment]
None of your code shows what's calling getID3. Your refernces to `meta.html` and `meta.php` indicate you're using some 3rd-party library/program of some kind.

You can see https://github.com/JamesHeinrich/getID3/blob/master/demos/demo.basic.php for a basic example of how to analyze a file with getID3.

**Comment by mpgradio** [comment]
> None of your code shows what's calling getID3. Your refernces to `meta.html` and `meta.php` indicate you're using some 3rd-party library/program of some kind.
> 
> You can see https://github.com/JamesHeinrich/getID3/blob/master/demos/demo.basic.php for a basic example of how to analyze a file with getID3.

sorry this might be better..
`<?php

require('ID3TagsReader.php');

// set error reporting level
if (version_compare(phpversion(), '5.3.0', '>=') == 1)
  error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
else
  error_reporting(E_ALL & ~E_NOTICE);


// gathering all mp3 files in 'mp3' folder into array
//$sDir = 'C:\\EZSTREAM\\CENTURY\\';
$sDir = './';
$aFiles = array();
$rDir = opendir($sDir);
if ($rDir) {
    while ($sFile = readdir($rDir)) {
        if ($sFile == '.' or $sFile == '..' or !is_file($sDir . $sFile))
            continue;

        $aPathInfo = pathinfo($sFile);
        $sExt = strtolower($aPathInfo['extension']);
        if ($sExt == 'mp3') {
            $aFiles[] = $sDir . $sFile;
        }
    }
    closedir($rDir);
}

// new object of our ID3TagsReader class
$oReader = new ID3TagsReader();

// passing through located files ..
$sList = $sList2 = '';
foreach ($aFiles as $sSingleFile) {
    $aTags = $oReader->getTagsInfo($sSingleFile); // obtaining ID3 tags info
	$aHeaders = $oReader->getMP3BitRateSampleRate($sSingleFile);
	
	$sList .= '<tr>';
	$sList .= '<td>'.$aTags['Title'].'</td>';
	//$sList .= '<td>'.$aTags['Author'].'</td>';
	//$sList .= '<td>'.$aTags['Album'].'</td>';
	//$sList .= '<td>'.$aTags['Composer'].'</td>';
	//$sList .= '<td>'.$aTags['AlbumAuthor'].'</td>';
	//$sList .= '<td>'.$aTags['Genre'].'</td>';
	$sList .= '<td>'.$aTags['Artist'].'</td>';
	$sList .= '<td>'.$aHeaders['bitRate'].'</td>';
	$sList .= '<td>'.$aHeaders['sampleRate'].'</td>';
	$sList .= '<td>'.$fileinfo['tags'].'</td>';
	$sList .= '<td><a href="edittags.php?Filename='.urlencode($sSingleFile).'"><button class="button"><font color="white"> Edit Tags</font></button></a></td>';
	$sList .= '</tr>';

    $sList2 .= '<tr>';
	$sList2 .= '<td>'.$aTags['Title'].'</td>';
	$sList2 .= '<td>'.$aTags['AlbumAuthor'].'</td>';
	$sList2 .= '<td>'.$aTags['Track'].'</td>';
	$sList2 .= '<td>'.$aTags['Encoded'].'</td>';
	$sList2 .= '<td>'.$aTags['Copyright'].'</td>';
	$sList2 .= '<td>'.$aTags['Publisher'].'</td>';
	$sList2 .= '<td>'.$aTags['OriginalArtist'].'</td>';
	$sList2 .= '<td>'.$aTags['URL'].'</td>';
	$sList2 .= '<td>'.$aTags['Comments'].'</td>';
	$sList2 .= '<td>'.$aTags['Year'].'</td>';
	$sList2 .= '<td>'.$aTags['Length'].'</td>';
	$sList2 .= '<td>'.$aTags['Lyric'].'</td>';
	$sList2 .= '<td>'.$aTags['Desc'].'</td>';
	$sList2 .= '</tr>';
}

// main output
echo strtr(file_get_contents('meta.html'), array('__list__' => $sList, '__list2__' => $sList2));

?>`

**Comment by JamesHeinrich** [comment]
This is not part of getID3:
```
require('ID3TagsReader.php');
// new object of our ID3TagsReader class
$oReader = new ID3TagsReader();
```
