### ISSUE TITLE
Audio tag versions

### ISSUE THREAD

**Issue by mpgradio** [JamesHeinrich/getID3#302]
Interested to know how to include Tag types

_removed copy-paste of `demo.simple.php`_

**Comment by JamesHeinrich** [comment]
If you just want to know what tag _types_ are in your file:
```
require_once('../getid3/getid3.php');
$getID3 = new getID3;
$ThisFileInfo = $getID3->analyze($filename);
$tagtypes = (!empty($ThisFileInfo['tags']) ? array_keys($ThisFileInfo['tags']) : array());
```

**Comment by mpgradio** [comment]
Thank you, very much..
As my folder of files as other PHP in it with the audio, is there a way to add an exclusion to only scan mp3?

**Comment by mpgradio** [comment]
Struggling a bit here... is this correct?
echo '<TD ALIGN="RIGHT">'. $tagtypes = (!empty($ThisFileInfo['tags']) ? array_keys($ThisFileInfo['tags']) : array()).'</TD>';
![image](https://user-images.githubusercontent.com/81822846/113457103-eb9daf00-93dc-11eb-806b-2debd51e1db2.png)

**Comment by JamesHeinrich** [comment]
> As my folder of files as other PHP in it with the audio, is there a way to add an exclusion to only scan mp3?
That would be entirely dependent on your loop code that you walk through the directory with. Something like this would replicate what your screenshot shows:

```
require_once('../getid3/getid3.php');
$dir = 'C:/Users/User/Desktop/';
$allowed_extensions = array('mp3','flac');
if ($dh = opendir($dir)) {
	echo '<table border=1 cellspacing=0 cellpadding=3>';
	echo '<tr><th>Artist</th><th>Title</th><th>Bitrate</th><th>Frequency</th><th>Time</th><th>Tag</th></tr>';
	while ($file = readdir($dh)) {
		$filename = $dir.DIRECTORY_SEPARATOR.$file;
		$ext = pathinfo($filename, PATHINFO_EXTENSION);
		if (in_array(strtolower($ext), $allowed_extensions)) {
			$getID3 = new getID3;
			$ThisFileInfo = $getID3->analyze($filename);
			$getID3->CopyTagsToComments($ThisFileInfo);

			echo '<tr>';
			echo '<td>'.@$ThisFileInfo['comments_html']['artist'][0].'</td>';
			echo '<td>'.@$ThisFileInfo['comments_html']['title'][0].'</td>';
			echo '<td align="right">'.round(@$ThisFileInfo['bitrate'] / 1000).' kbps</td>';
			echo '<td align="right">'.@$ThisFileInfo['audio']['sample_rate'].'</td>';
			echo '<td align="right">'.@$ThisFileInfo['playtime_string'].'</td>';
			echo '<td>'.htmlentities(!empty($ThisFileInfo['tags']) ? implode(',', array_keys($ThisFileInfo['tags'])) : '').'</td>';
			echo '</tr>';
		}
	}
	closedir($dh);
	echo '</table>';
}
```

**Comment by mpgradio** [comment]
Thank you so very much, I have to say that you are always top-notch. 
getID3 rocks!! :)

**Comment by mpgradio** [comment]
This what I have so far but I don't think my loop is correct....to filter.

`<?php
// include getID3() library (can be in a different directory if full path is specified)
require_once('./getid3/getid3.php');

// Initialize getID3 engine
$getID3 = new getID3;

$DirectoryToScan = './'; // change to whatever directory you want to scan
$dir = opendir($DirectoryToScan);
echo '<TABLE BORDER="1" CELLSPACING="0" CELLPADDING="3">';
echo '<TR><TH>Artist</TH><TH>Title</TH><TH>Bitrate</TH><TH>Frequency</TH><TH>Time</TH><TH>Tag</TH></TR>';
while (($file = readdir($dir)) !== false) {
	$FullFileName = realpath($DirectoryToScan.'/'.$file);
	
	$allowed_extensions = array('mp3','flac');
	
	if (is_file($FullFileName)) {
		set_time_limit(30);

		$ThisFileInfo = $getID3->analyze($FullFileName);

		getid3_lib::CopyTagsToComments($ThisFileInfo);

		// output desired information in whatever format you want
		
		echo '<tr>';
			echo '<td>'.@$ThisFileInfo['comments_html']['artist'][0].'</td>';
			echo '<td>'.@$ThisFileInfo['comments_html']['title'][0].'</td>';
			echo '<td align="right">'.round(@$ThisFileInfo['bitrate'] / 1000).' kbps</td>';
			echo '<td align="right">'.@$ThisFileInfo['audio']['sample_rate'].'</td>';
			echo '<td align="right">'.@$ThisFileInfo['playtime_string'].'</td>';
			echo '<td>'.htmlentities(!empty($ThisFileInfo['tags']) ? implode(',', array_keys($ThisFileInfo['tags'])) : '').'</td>';
			echo '</tr>';

		echo '</TR>';
	}
}
echo '</table>';
?>
`

**Comment by JamesHeinrich** [comment]
Because you're not checking for the extension.
```
$allowed_extensions = array('mp3','flac');
$ext = pathinfo($FullFileName, PATHINFO_EXTENSION);
if (is_file($FullFileName) && in_array(strtolower($ext), $allowed_extensions)) {
```

**Comment by mpgradio** [comment]
Crap, I had that mixed up and failed to place it here...thank you.

`$FullFileName = realpath($DirectoryToScan.'/'.$file);
	
		$allowed_extensions = array('mp3','flac');
		$ext = pathinfo($FullFileName, PATHINFO_EXTENSION);
		if (is_file($FullFileName) && in_array(strtolower($ext), $allowed_extensions)) {
		
		set_time_limit(30);`
