### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by jonnitto** [JamesHeinrich/getID3#303]
When do you will release version 2 as a stable release?

**Comment by JamesHeinrich** [comment]
Me, personally, probably never. I am only maintaining the v1.9.x branch, some other contributors are porting my changes over to the v2.x branch. If they get to the point where they would like to release a stable version I'm not opposed to that, but I'm not sufficiently comfortable with the paradigm changes in v2 to feel qualified lead development there.
