### ISSUE TITLE
Undefined index: comments

### ISSUE THREAD

**Issue by RemiHin** [JamesHeinrich/getID3#304]
Undefined index: comments

  at vendor/james-heinrich/getid3/getid3/getid3.lib.php:1607
    1603▕ 				'tracknumber' => 'track_number',
    1604▕ 				'track'       => 'track_number',
    1605▕ 			);
    1606▕ 			foreach ($StandardizeFieldNames as $badkey => $goodkey) {
  ➜ 1607▕ 				if (array_key_exists($badkey, $ThisFileInfo['comments']) && !array_key_exists($goodkey, $ThisFileInfo['comments'])) {
    1608▕ 					$ThisFileInfo['comments'][$goodkey] = $ThisFileInfo['comments'][$badkey];
    1609▕ 					unset($ThisFileInfo['comments'][$badkey]);
    1610▕ 				}
    1611▕ 			}

**Comment by JamesHeinrich** [comment]
Fixed in https://github.com/JamesHeinrich/getID3/commit/e54782d655120e5993ceeca9fb0e01895255ed07
