### ISSUE TITLE
PHP 8 error trying to access index of array value 

### ISSUE THREAD

**Issue by alexbirtwell** [JamesHeinrich/getID3#312]
https://github.com/JamesHeinrich/getID3/blob/464f9cb06bccdfbd29df4abe256de24e3877d06b/src/WriteTags.php#L656

Will PR but requires line changing to below or similar

if (ord(substr($value,$i,1)) > 127) {

**Comment by JamesHeinrich** [comment]
Perhaps you can explain further, I'm not sure why this would need to be changed? Can you give an example of how/where/why the current code wouldn't work as expected?

**Comment by alexbirtwell** [comment]
When running WriteTags() in PHP8 the existing code generates the error: "accessing array value of int" line 656 in getID3/src/WriteTags.php. The code is using the [] to access character $i of the integer which is no longer supported in PHP8.

**Comment by alexbirtwell** [comment]
I should probably add that we are now using our Fork of 2.0 beta 3 in a production environment on PHP8 for reading and writing id3 tags on mp3 and video files and it is working flawlessly.

**Comment by StudioMaX** [comment]
I don't see any practical sense in the change you provided. You have replaced access by offset with substr, what is mostly the same.
Look: https://3v4l.org/oXYWJ
In which version is this bug reproduced? Namely, what value is indicated in `getID3::VERSION`?

**Comment by alexbirtwell** [comment]
Sorry for the confusion, the access by offset on int doesn't appear to be supported in PHP8 or certainly is causing a fatal error?

e.g. 
$int = 1234;
echo $int[2];

results in fatal error 
ErrorException
Trying to access array offset on value of type int

Version - 2.0.x-202104081001'

**Comment by StudioMaX** [comment]
https://github.com/JamesHeinrich/getID3/blob/464f9cb06bccdfbd29df4abe256de24e3877d06b/src/WriteTags.php#L653-L659
This is the code you are linking to. There is casting `$value` to a string. It is not an integer or an array, but a string.
If you have some error in this place, please attach an example file here (or send it to info@getid3.org) and a sample code with which you want to save the file.
