### ISSUE TITLE
Error checking for non-seekable streams

### ISSUE THREAD

**Issue by defunctl** [JamesHeinrich/getID3#327]
Hey James,

I've read you said you don't support non-local streams but PHP does state that not all streams support seeking and there are many places in the code where that's not checked.

For example, [the logic that begins here](https://github.com/JamesHeinrich/getID3/blob/master/getid3/module.audio.mp3.php#L1450) ends up creating a long running loop that continues to try to seek until it basically times out when using a remote stream wrapper like s3/Azure.

Mind you, this is in the version [WordPress is maintaining](https://github.com/WordPress/WordPress/blob/5.7-branch/wp-includes/ID3/module.audio.mp3.php#L1436).

I can see that `$SyncSeekAttemptsMax` was added in master, which would definitely help my situation, but it would be even better if we just checked if the stream supported seeking as well, just a simple example:

```php
		if ($this->fseek($avdataoffset) === -1) {
			$this->error('Unable to seek this file stream');
			return false;
		}
```
Just in case, it's important to note that [fseek()](https://www.php.net/manual/en/function.fseek.php) returns 0 on success and -1 otherwise. Most StreamWrapper implementations will check if their stream is seekable and if not, have [streamWrapper::stream_seek](https://www.php.net/manual/en/streamwrapper.stream-seek.php) return false, which would ultimately make `fseek()` return -1.

Or, perhaps it would be better to throw an `getid3_exception` by checking the result in [getID3::fseek()](https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L2258) instead and just fail early?

If you need any other information, please let me know.

Thanks!

**Comment by JamesHeinrich** [comment]
If you'd like to make a PR with your suggest changes I'll be happy to merge it.

**Comment by defunctl** [comment]
Hey @JamesHeinrich I think I'd go with the strategy of updating [getID3::fseek()](https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L2258) to throw a `getid3_exception` if seeking failed.

Does that sound like the best strategy to try?

**Comment by JamesHeinrich** [comment]
That's fine with me.
