### ISSUE TITLE
Script dumps an array of data

### ISSUE THREAD

**Issue by Peter-K-Joseph** [JamesHeinrich/getID3#331]
Hey, while working with a project of mine, I noticed that while analyzing some files the code returns this

`array(4) {
  ["long_version"]=>
  string(20) "LAME3.99r�.Y4"
  ["short_version"]=>
  string(9) "LAME3.99r"
  ["numeric_version"]=>
  string(5) "3.99r"
  ["integer_version"]=>
  array(2) {
    [0]=>
    int(3)
    [1]=>
    int(99)
  }
}`

Any idea how to remove this?

**Comment by JamesHeinrich** [comment]
Apparently I left some debugging info in when working on https://github.com/JamesHeinrich/getID3/issues/207
Removed in https://github.com/JamesHeinrich/getID3/commit/b9974f80d297b305c5a5ccd2dd66bff2bb73c62b
