### ISSUE TITLE
PHP Deprecated:  Array and string offset access syntax 

### ISSUE THREAD

**Issue by jilaan** [JamesHeinrich/getID3#332]
I face this issue on getid3.php file here is an issue 

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in

$this->info['id3v2']['majorversion']  = ord($header{3});
$this->info['id3v2']['minorversion']  = ord($header{4});

how can i fix it?

Thanks

**Comment by JamesHeinrich** [comment]
It was already fixed long ago:
https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L697-L698
You should probably update your getID3 installation.
