### ISSUE TITLE
Add example files to tests/files/

### ISSUE THREAD

**Issue by duncan3dc** [JamesHeinrich/getID3#34]
We need some test files that we can run our test suite against. We have one for mp3, but nothing else.
They should be small files to keep the size of the repo down

**Comment by soulhunter1987** [comment]
Yes, it is a problem to collect a good test collection because many files are, first of all, lagre, and second, copyright-protected. But of couse, we need a test/demo collection. I think that create a new repo as sujested is a good idea. We will move demo code there and put some samples. Also automated tests should me moved there till there would be no sample files to perform tests in basic getID3 repo. Demo/test repo will require getID3 as a dependency via composer and it will be something like a "visual" representation of getID3. So if one would like to run demos, he will need to get getID3 demo repo, not the library itself. I sugest repo name "getID3-demo".

**Comment by soulhunter1987** [comment]
James, could you, please, create a new repo and grant me full access to it?

**Comment by duncan3dc** [comment]
It would make sense to keep the test suite in this repository, and require the new repository (containing tests files, demos, etc) in via composer (using require-dev).

The main reason for this (besides standard practise) is Travis is triggered by pushes to this repo

**Comment by JamesHeinrich** [comment]
Sorry, I've been away for a bit. Does this help?
https://github.com/JamesHeinrich/getID3-testfiles

**Comment by duncan3dc** [comment]
Thanks James. I've been thinking about this more and we should be able to create plenty of tests without requiring those files. I'm hoping to find some time to dedicate to getid3 soon so I'll let you know if I need anything on that front.

Certainly we'll want to run the 2.0 release through your test suite before releasing if possible

**Comment by duncan3dc** [comment]
Sorry guys but I'm just finding it too much work to bring all the modules to a standard I'm happy with, I keep getting tied up in knots trying to refactor everything...
![refactor](https://cloud.githubusercontent.com/assets/546811/7755875/470cd2cc-ffef-11e4-9d7d-6b433e951c28.gif)

So I'm gonna bow out and try to write my own audio tagging library that just focuses on MP3s.

@JamesHeinrich Thanks very much for being so welcoming and permissive with your code, it's truly appreciated and you've built something great here.

@soulhunter1987 Best of luck if you decide to carry on with this 2.0 branch, I'm certainly on hand if you want to ping me and ask any questions

**Comment by Gemorroj** [comment]
@duncan3dc https://github.com/duncan3dc/meta-audio this will be your repository?

**Comment by duncan3dc** [comment]
@gemorroj That's the plan

**Comment by hassankhan** [comment]
Hi @JamesHeinrich, was wondering if there was any chance you could push some of your test files to that repo you created? :smile:

**Comment by JamesHeinrich** [comment]
I filtered down the 30GB of test files to a more reasonable 2GB, and my poor internet is trying to upload that now... check back tomorrow :)

**Comment by JamesHeinrich** [comment]
Sigh. The sync failed, and then proceeded to delete my local copy of the data. So I'll need to spend another 2 hours re-creating the local repository and re-try the upload later.

**Comment by hassankhan** [comment]
Thanks, really appreciate it :smile:

**Comment by JamesHeinrich** [comment]
So far about 75% done... should be done by the end of today, will post again when it is.

**Comment by JamesHeinrich** [comment]
And, finally, all uploaded.
