### ISSUE TITLE
several megabyte id3 crashing mysql

### ISSUE THREAD

**Issue by hayden-t** [JamesHeinrich/getID3#340]
I have this odd episode of a show that id3 is generating like a ~4MB meta from. This is going over the max_allowed_packet limit on mysql, the vaule is in quicktime moov.
[bug.txt](https://github.com/JamesHeinrich/getID3/files/7095059/bug.txt)

**Comment by hayden-t** [comment]
I found this setting $getID3->options_audiovideo_quicktime_ReturnAtomData = false; which drops the 'bad' data, maybe it should be by default this considering how 'bad' it is, and that its just going to fill your db with junk.

**Comment by JamesHeinrich** [comment]
I'm ok with defaulting quicktime.ReturnAtomData=false, changed in https://github.com/JamesHeinrich/getID3/commit/4788e3ed248b0643da73f1b4b2a94e2f52f71e48

**Comment by hayden-t** [comment]
cheers
