### ISSUE TITLE
Bug: mb_basename() is not PHP v8.1 compatible

### ISSUE THREAD

**Issue by dleffler** [JamesHeinrich/getID3#345]
PHP v8.1 doesn't allow nulls to be passed as parameters for several built-in functions such as basename() therefore to prevent a deprecation warning the function definition for mb_basename() in getid3.lib.php should be changed from:
```
public static function mb_basename($path, $suffix = null)
```
to
```
public static function mb_basename($path, $suffix = '')
```

**Comment by StudioMaX** [comment]
Please update getID3 to the latest version. This already was fixed by https://github.com/JamesHeinrich/getID3/pull/335.
