### ISSUE TITLE
Need a simple function

### ISSUE THREAD

**Issue by generalp2** [JamesHeinrich/getID3#350]
With apologies for my last confusing post, let me break down what I am seeking. 

I need a procedural php function where I would provide as arguments: a filename (of most any image type or video type), desired output type. desired output width, and desired output height, and have the function return the converted image, its orientation, and size (in bytes). Does such a function exist in getID3 (which I have loaded)? Even a close example would help.

**Comment by JamesHeinrich** [comment]
getID3 will likely be able to return the existing format/width/height for an input image/video, but it has no capability for conversion to other format. Nor does it even understand the actual image involved, only the metadata is parsed.

**Comment by generalp2** [comment]
Hi James,

You are dealing with a highly-experienced amateur here… 😊 By that I mean I have been coding php for 3+ years but this is my first encounter with images. 

What would be the procedural php for getting the existing format/width/height for an input image/video? I tried several examples I found online but could not get them to work. Any help is greatly appreciated.

Chuck

**Comment by JamesHeinrich** [comment]
The most basic example is given in https://github.com/JamesHeinrich/getID3/blob/master/demos/demo.basic.php
This will analyze whichever file:
```
require_once('../getid3/getid3.php');
$getID3 = new getID3;
$ThisFileInfo = $getID3->analyze($filename);
```
Then `$ThisFileInfo` will contain all the information about the file. Things you have mentioned include:
`$ThisFileInfo['fileformat']`
`$ThisFileInfo['video']['resolution_x']` and `$ThisFileInfo['video']['resolution_y']`
You can `print_r($ThisFileInfo)` to see all the data that is being returned, it may be overwhelming. If you open demo.browse.php in your browser and point it to a file you're interested in it may be easier to see what's being returned where.

**Comment by generalp2** [comment]
Many thanks. I will try this tomorrow night.

Chuck

**Comment by generalp2** [comment]
Hi James,

Thanks for this. Your help is greatly appreciated. It is exactly what I needed. It is a big help. 

Would you know a routine (procedural)  that would convert media with formats of .MOV, .AVI, and .MTS into .MP4?

Charles

**Comment by JamesHeinrich** [comment]
If you want a command-line video conversion tool the first thing that comes to mind is ffmpeg, but I don't know it nearly well enough to advise you on specific command and settings.

**Comment by generalp2** [comment]
Thanks. I have that tool and have been testing it. GetID3 is working for my dimensions and type, so next will be testing the conversation. 
Charles
