### ISSUE TITLE
Errors with PHP 8.1

### ISSUE THREAD

**Issue by gandalf458** [JamesHeinrich/getID3#353]
Running my application using PHP 8.1 I am getting the following errors:

Deprecated: basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in C:\laragon\www\...\getID3\getid3\getid3.lib.php on line 1799

Deprecated: Automatic conversion of false to array is deprecated in C:\laragon\www\...\getID3\getid3\module.audio-video.quicktime.php on line 2067

**Comment by StudioMaX** [comment]
What value is in `getID3::VERSION`?

> Deprecated: basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in C:\laragon\www...\getID3\getid3\getid3.lib.php on line 1799

Most likely this has already been fixed in #335.

> Deprecated: Automatic conversion of false to array is deprecated in C:\laragon\www...\getID3\getid3\module.audio-video.quicktime.php on line 2067

More details are needed in which version this happened. This warning is quite likely if it hasn't been fixed yet.

**Comment by gandalf458** [comment]
Many thanks. I'll check

**Comment by gandalf458** [comment]
I am a numpty. I should have tried with the latest version!
