### ISSUE TITLE
Some MPEG-2 streams result in corrupt width/height

### ISSUE THREAD

**Issue by brion** [JamesHeinrich/getID3#360]
This is a followup to https://github.com/JamesHeinrich/getID3/pull/359 where I was seeing divide-by-zero errors that I couldn't explain in MPEG videos.

I found a file that triggers the error condition; the problem seems to be that there are multiple blocks of data read out of the file, overwriting the data that's been loaded so far; initially getid3 correctly reads 720x480 but eventually it replaces it with 0x1, which was leading to the divide by zero when processing the aspect ratio.

Possibly there's a bad block at the end of the file? But ffpprobe -show_frames shows nothing out of the ordinary I could see.

Sample (about 800 MiB)
https://upload.wikimedia.org/wikipedia/commons/b/ba/Born_of_a_Dream_-_Extra_Feature.mpg

Repro:

```php

<?php

require __DIR__ . '/vendor/autoload.php';

$files = ['Born_of_a_Dream_-_Extra_Feature.mpg'];
foreach ( $files as $path ) {
    echo "$path\n";

    // Create new id3 object:
    $getID3 = new getID3();

    // Don't grab stuff we don't use:
    // Read and process ID3v1 tags
    $getID3->option_tag_id3v1 = false;
    // Read and process ID3v2 tags
    $getID3->option_tag_id3v2 = false;
    // Read and process Lyrics3 tags
    $getID3->option_tag_lyrics3 = false;
    // Read and process APE tags
    $getID3->option_tag_apetag = false;
    // Copy tags to root key 'tags' and encode to $this->encoding
    $getID3->option_tags_process = false;
    // Copy tags to root key 'tags_html' properly translated from various encodings to HTML entities
    $getID3->option_tags_html = false;

    // Analyze file to get metadata structure:
    $id3 = $getID3->analyze( $path );
}

```

Expected result: no error

Actual result: Divide By Zero fatal error (using the 3.0.19 composer release which doesn't have the workaround to prevent division error).

**Comment by brion** [comment]
(I'll do another run on this later to see if I can figure out exactly why it's eating the resolution markers. Happy holidays yall ;) )

**Comment by JamesHeinrich** [comment]
The sample file you linked does not produce any errors for me (once your `$width != 0` patch from #359 is included), at least on PHP v7.4.1. The width and height values seem to be returned as expected.
Presumably this is happening when videoAspectRatioLookup is called on [line 129](https://github.com/JamesHeinrich/getID3/blob/master/getid3/module.audio-video.mpeg.php#L129) without the optional width/height parameters which could then fall through to the divide-by-zero. I haven't looked closer at the file to see what's happening in any more detail.

Are you still getting errors?

**Comment by brion** [comment]
Got back to this after holiday break -- indeed, everything seems to recover once the divide-by-zero guard is present. This seems to be because the _next_ such frame resets the width and height, and the aspect ratio, to correct values. It's worrisome to me somehow that there's frames getting interpreted as 0 weight and 1 height, but I've got multiple files with it so .... it happens. ;)

Anyway, looks like we're good on this; I've got one other unguarded use of an array bit that sometimes isn't initialized which I'll file separately (since this can show a notice-level warning)

**Comment by StudioMaX** [comment]
I also found one similar file with a similar problem (width 0 and height 1 pixels). Most likely this is some kind of special frame, since all values in the `$bitstream` are broken, not just the height and width. But at the same time they preserve some order, since the height and width are always 0/1.

https://github.com/JamesHeinrich/getID3/blob/46346ff3bea96a63f1a1d58ee4eabc79471d0ec8/getid3/module.audio-video.mpeg.php#L101-L105

Ideally, this frame should be ignored altogether so as not to spoil the data already received from the previous frames. But as you noticed, correct data appears in the following frames, which overwrites the bad data from this bad frame.
