### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by QuixThe2nd** [JamesHeinrich/getID3#366]
Im getting the following errors:
`Undefined array key 5`
`Undefined array key 6`
on `line 1702` of `getID3/module.audio-video.quicktime.php`

PHP Version: 8.0.14

File: https://starfiles.co/file/nT77EjZPL3Nb/cool-mov

**Comment by StudioMaX** [comment]
What value is in `getID3::VERSION`?
I don't see any warnings with this file on PHP 8.0/8.1.

**Comment by QuixThe2nd** [comment]
1.9.21-202201031158

**Comment by JamesHeinrich** [comment]
The line in question is this:
`$atom_structure['key_name'] = @$info['quicktime']['temp_meta_key_names'][$metaDATAkey++];`
If I remove the error-suppressing `@` then I do also get the same undefined-array-key notices.
I also tested this file on PHP v8.0.11 and didn't get any warnings with the `@` in place, but I have changed to a more explicit check in https://github.com/JamesHeinrich/getID3/commit/2279f7caca2d761dfc580dd02b401e7a1ff69dfe

**Comment by StudioMaX** [comment]
Just wanted to opine that I didn't see any warnings at this line on PHP 8.0/8.1 either, even under xdebug. And I'm even wondering how this warning appeared by ignoring `@`.
