### ISSUE TITLE
Wrong width and height info for Videos captured in Android

### ISSUE THREAD

**Issue by UtkuDalmaz** [JamesHeinrich/getID3#370]
I discovered something strange behavior

When I try to get info of a video that was captured in Android devices getid3 gives the wrong info for width and height info

Normally resolution_x is the width and resolution_y is height but for Android videos, resolution_x shows the height, and resolution_y shows the width

For example please try with this file
https://filetransfer.io/data-package/EPzTvE6o#link

**Comment by StudioMaX** [comment]
Your video also has a "rotate" property. You can find more details here:
https://www.getid3.org/phpBB3/viewtopic.php?t=1908
https://www.getid3.org/phpBB3/viewtopic.php?t=2468

Someone also posted sample code for detecting such rotated videos: 
```php
<?php
include_once('getid3/getid3.php');

$filename = "clip.mov";

$getID3 = new getID3;
$file = $getID3->analyze($filename);

$width = $file['video']['resolution_x'];
$height = $file['video']['resolution_y'];
$rotate = $file['video']['rotate'];

$width = $file['video']['resolution_x'];
$height = $file['video']['resolution_y'];

if($file['video']['rotate'] == 90 || $file['video']['rotate'] == 270) {
	echo "Height: ".$width."<br><br>";
	echo "Width: ".$height."<br><br>";
} else {
	echo "Height: ".$height."<br><br>";
	echo "Width: ".$width."<br><br>";
}
echo "Rotate: ".$rotate;
```

**Comment by JamesHeinrich** [comment]
StudioMaX answered faster (and better) than I could, thanks :)

The video is truly 1920 wide and 1080 tall, but with the rotation flag set to display the video as rotated 90° (clockwise) on playback in rotation-aware players. If you play the video in older software that is not rotation-aware it will display landscape with the peoples' heads to the left.
