### ISSUE TITLE
Error while writing tag on WAV files

### ISSUE THREAD

**Issue by cybadr** [JamesHeinrich/getID3#381]
Hi,
When we want to write id3v1/id3v2 tag on wav file :
`PHP_DEPRECATED] vendor/james-heinrich/getid3/getid3/module.audio-video.riff.php at line 1696 Automatic conversion of false to array is deprecated` 

This appears on last stable version.

The problem is also present on v2.0.0-beta4
`vendor/james-heinrich/getid3/src/Module/AudioVideo/Riff.php at line 1691 Automatic conversion of false to array is deprecated
`

After it results on 
`Tag format "id3v1" is not allowed on "wav.wav" files`

We use PHP version 8.1

**Comment by JamesHeinrich** [comment]
Can you provide a sample WAV file that generates this warning?

Can you confirm what you're referring to as line 1696 is this line:
`$RIFFchunk[$chunkname][$thisindex]['offset'] = $this->ftell() - 8;`

As for the "id3v1" not allowed on "wav.wav" message, that's correct and won't change.

**Comment by sunilshenoy** [comment]
I have been coming across the same error i.e `Automatic conversion of false to array is deprecated` and the line 

`$RIFFchunk[$chunkname][$thisindex]['offset'] = $this->ftell() - 8;`

and 

`$RIFFchunk[$listname] = array();`

is what the pipeline is pointing towards. 

This is for PHP 8.1. PHP 7.3 does not return this warning.

**Comment by StudioMaX** [comment]
@sunilshenoy Please provide a sample file.

**Comment by sunilshenoy** [comment]
Was not able to upload AVI file using Github issues. Have uploaded the file here:

https://jmp.sh/FqGjEaI

Thank you

**Comment by JamesHeinrich** [comment]
I took a quick look at that file under PHP 7.4 and 8.0 and didn't see anything unusual. I don't have a PHP 8.1 environment available to test with right now. Perhaps @StudioMaX can spot something I missed.

**Comment by sunilshenoy** [comment]
https://github.com/JamesHeinrich/getID3/commit/29f31182125a0f28d69f114743c9da1880f1e4fd

This commit with this line

https://github.com/JamesHeinrich/getID3/blob/master/getid3/module.audio-video.riff.php#L1585

might be the change needed to fix the Deprecation notice. Will update our my code and report back here.

**Comment by StudioMaX** [comment]
@JamesHeinrich Could you release a new minor version? More than a year has passed since the release of the current stable 1.9.21, and there are many fixes in the `master`.

**Comment by JamesHeinrich** [comment]
I will tag a new release once @sunilshenoy reports back with a fix for this current issue.

**Comment by StudioMaX** [comment]
I checked in version 1.9.21 and this warning appeared, but in the current `master` this is already fixed just by the [above commit](https://github.com/JamesHeinrich/getID3/commit/29f31182125a0f28d69f114743c9da1880f1e4fd#diff-4b03799e108b82689dd2f2af5d1b1c42f97f60836cbdbe5b5cf9b8d52fe3763bR1585).
@sunilshenoy please confirm that you don't get this warning in the `master` branch?

**Comment by sunilshenoy** [comment]
Just finished running the pipeline on our local repo and dont see the warnings any more in the ```master``` branch.

**Comment by JamesHeinrich** [comment]
> @JamesHeinrich Could you release a new minor version? More than a year has passed since the release of the current stable 1.9.21, and there are many fixes in the `master`.

Tagged new release v1.9.22
https://github.com/JamesHeinrich/getID3/releases/tag/v1.9.22
