### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by wbartels** [JamesHeinrich/getID3#383]
I have created a GNU GPL 3 web application (netjukebox.nl) witch includes getID3().
In the GUI license notice should I include getID3() with **GNU GPL 3** or **GNU LGPL 3**? 

Thanks,
Willem

**Comment by JamesHeinrich** [comment]
I'm _really_ not an expert on licensing, perhaps someone who knows more would care to respond.
If your application is GPL3 then I would assume you'd also include getID3 as GPL3 -- do you have any reason not to?
