### ISSUE TITLE
Deprecated: Automatic conversion of false to array is deprecated in...module.audio-video.riff.php on line 1696

### ISSUE THREAD

**Issue by janui** [JamesHeinrich/getID3#386]
Hi There,

When retrieving metadata tags from a '.wav' file I am getting the following error:
'Deprecated: Automatic conversion of false to array is deprecated in /srv/http/app/libs/vendor/james-heinrich/getid3/getid3/module.audio-video.riff.php on line 1696'
The routine then continues to run for a long time (indefinitely?).

I have two '.wav' files which both reproduce the problem. You can find them is here (there are two wav files and one dff, click them and then there is a button on the player to actually download them):
https://www.hifistatement.net/download/item/1077-zur-feier-der-kooperation-mit-positive-feedback-ein-kostenloser-download?start=2

I am running arch arm Linux: 5.10.95-2, PHP: 8.1.2-1 and getid3 as a Composer package: v1.9.21

getid3 is a great utility please keep up the good work.

janui

**Comment by JamesHeinrich** [comment]
I just tested it with those 3 sample files on PHP v8.0.11 without problem.
Can you please confirm what your `line 1696` in `module.audio-video.riff.php` looks like? Does it look like the current version?
https://github.com/JamesHeinrich/getID3/blob/master/getid3/module.audio-video.riff.php#L1696

**Comment by janui** [comment]
Thanks for the very fast reply. No, my version is different, however my version is the latest composer version.
I will attempt to upgrade using your latest files on github. Will get back to you.

**Comment by janui** [comment]
I have installed the git hub master version of getID3. The line 1696 now matches and the errors have disappeared, but...
getID3 is lightning fast for all file types except the '.wav' files. The '.wav' files are processed without errors, but it takes ages. Is this to be expected? Or am I missing something?

**Comment by JamesHeinrich** [comment]
The three example files parse in about 0.025s each on my test system.

**Comment by janui** [comment]
Thanks, for confirming this. I am closing this issue.

I will dig into the slow response. If I find anything I will open another ticket. Thanks again for the excellent support.
