### ISSUE TITLE
fails to detect h265 video codec

### ISSUE THREAD

**Issue by robert777robert777** [JamesHeinrich/getID3#387]
fails to detect h265 video codec (actually it doesn't display fourcc of any video codec not whitelisted in module.audio-video.quicktime.php)
the fourcc is hvc1.

**Comment by JamesHeinrich** [comment]
Do you have a sample file to test with, please?

**Comment by JamesHeinrich** [comment]
Fixed in https://github.com/JamesHeinrich/getID3/commit/59439c58bfeedcfac551bef0d0ec9a2050b1a374
Thanks for the bug report.
