### ISSUE TITLE
utf8_encode/decode deprecated in PHP 8.2

### ISSUE THREAD

**Issue by zerocrates** [JamesHeinrich/getID3#389]
See https://wiki.php.net/rfc/remove_utf8_decode_and_utf8_encode

These are used just barely, in the iconv fallback codepaths in getid3.lib.php, and there are fallbacks for them being missing (from when they used to be in the XML extension and so might not been available for some installs).

A simple option might be to just take out the calls to these and instead always use the "fallback fallbacks" that are already there.

**Comment by JamesHeinrich** [comment]
Since they're wrapped in `if (function_exists('utf8_encode')) {` checks it shouldn't break anything even in PHP9 when those functions are removed entirely.

**Comment by zerocrates** [comment]
Yeah, it won't break anything. You'll just get deprecation warnings from 8.2 until 9.
