### ISSUE TITLE
Can we extract dynamic range of an audio file ?

### ISSUE THREAD

**Issue by Mentia** [JamesHeinrich/getID3#390]
I see that there is somewhere in the code a dynamicrange tag. But it does not seem to be used.

Is there a way to get the DR of the audio file (flac, dsf) ?

Thx for a great tool !

**Comment by JamesHeinrich** [comment]
If that data is stored somewhere in the metadata then getID3 probably already extracts it.
If you mean decode the audio and calculate the value from the audio data itself then no, that is beyond the scope of getID3.
