### ISSUE TITLE
Function getid3_lib::ImageTypesLookup has been deleted

### ISSUE THREAD

**Issue by jpyrat** [JamesHeinrich/getID3#391]
Hi,

I use this function in my code and it has been deleted from the code of the lib with no notice in the changelog (1.9.21).

Could you put it back ?

Regards

**Comment by StudioMaX** [comment]
Looks like it was removed since 1.9.16 (released at 17 Oct 2018) with this commit: https://github.com/JamesHeinrich/getID3/commit/9df2674ad187e106b31b45a297a40f805b08d074
Just replace it in your code with native `image_type_to_mime_type`.

**Comment by JamesHeinrich** [comment]
It was removed 4+ years ago in v1.9.15-201803150911 in https://github.com/JamesHeinrich/getID3/commit/9df2674ad187e106b31b45a297a40f805b08d074
Native PHP function [image_type_to_mime_type](https://www.php.net/manual/en/function.image-type-to-mime-type.php) does the same thing (when getID3 was first written PHP 4.3 wasn't released yet, hence the custom function).
