### ISSUE TITLE
Wrong song duration

### ISSUE THREAD

**Issue by Afterster** [JamesHeinrich/getID3#41]
On some files getID3 return th wrong song duration whereas it is fine on media players or mediainfo.
Please download a test file here: http://dropcanvas.com/v4qye (expires in 3 days)

Thank you.

**Comment by henryford** [comment]
Hi,

I initially opened the issue with ampache - I can provide the test file if necessary. 

Any updates on this issue?

Thanks

**Comment by JamesHeinrich** [comment]
I did download the supplied test file but I haven't yet figured out what the underlying cause of the problem is.

**Comment by JamesHeinrich** [comment]
I have added a patch in https://github.com/JamesHeinrich/getID3/commit/ed9e77959015d61bf93fe144d552f27d58397099

The provided sample file included a Xing-style VBR header but without the VBR_bytes portion specified. The header frame is 32kbps, the rest of the audio file is 320kbps hence the playtime was off by a factor of 10x.

**Comment by Afterster** [comment]
Thanks!

**Comment by henryford** [comment]
Thanks - good find!
