### ISSUE TITLE
Incorrect audio metadata with some MP4 files

### ISSUE THREAD

**Issue by gino0631** [JamesHeinrich/getID3#413]
QuickTime audio metadata (sample rate, bit depth, channels) is incorrect for some MP4 files, for instance, with the sample in the original issue gino0631/nextcloud-metadata#96 getID3 (verified with the latest release v1.9.22) reports:
```
quicktime.audio.codec:	
quicktime.audio.sample_rate:	6400
quicktime.audio.channels:	0
quicktime.audio.bit_depth:	12800
```
The expected values are:
![Expected](https://user-images.githubusercontent.com/66261502/213156131-37bcf8b7-54b7-4f0c-8502-4c68ea7ee031.png)

The sample is [here](https://user-images.githubusercontent.com/13659309/228863637-024f0c30-710f-4a06-b327-637b538e55c6.mp4).

**Comment by gino0631** [comment]
Cool, thanks! Yes, I know it is a mess with no consistent documentation, and really appreciate your efforts.

**Comment by gino0631** [comment]
As for the logic, I would take a look at other tools, MediaInfo for example - I don't have an exact suggestion how to handle this particular case correctly.

**Comment by JamesHeinrich** [comment]
The simple change I made in https://github.com/JamesHeinrich/getID3/commit/4efd6d75b396e7067b9958c6bfd12d3ad6c45a75 should fix this issue, and hopefully not break other things.
