### ISSUE TITLE
Purchasing a commercial license

### ISSUE THREAD

**Issue by NoBodyButMe** [JamesHeinrich/getID3#417]
This is the most weird way to sell a license. Your site doesn't show any price at al. You can just click on the paypal button without mentioning a price. Your sales site is also completely free of privacy terms, terms of sale, etc. It is totally non-compliant with European legislation. What a strange way to sell licences. In fact, this is completely illegal in Europe.

**Comment by JamesHeinrich** [comment]
gCL licenses are no longer offered, thanks for the reminder, I have updated the website.
