### ISSUE TITLE
PHP Error as Severity: Notice  Message: Undefined index: time_scale  Filename: getid3/module.audio-video.quicktime.php  Line Number: 335

### ISSUE THREAD

**Issue by nagesh-nano** [JamesHeinrich/getID3#419]
I am getting an PHP error for a specific video file as above 
```
Severity: Notice

Message: Undefined index: time_scale

Filename: getid3/module.audio-video.quicktime.php

Line Number: 335
```
Maybe there should be an isset() or array_key_exist() condition to check time_scale key
Attached video is playing in vlc media player.

https://github.com/JamesHeinrich/getID3/assets/99026217/51482f33-9bfe-402a-873f-4a32fb571b20

**Comment by JamesHeinrich** [comment]
Thanks. Fixed in https://github.com/JamesHeinrich/getID3/commit/6a8cc002dfc1cb9975e7899b9b89163bff72ddc0
