### ISSUE TITLE
tven and hdvd are missing from module.audio-video.quicktime.php

### ISSUE THREAD

**Issue by wagnered** [JamesHeinrich/getID3#42]
tven and hdvd are described at https://code.google.com/p/mp4v2/wiki/iTunesMetadata
and are incorporated into MetaX a commercial product  created by Dan Hinsley who confirmed to me that it strictly adheres to the iTunes specs.

I am using the app for supporting the Ampache development so I added the appropriate code to:

QuicktimeParseAtom();
CopyToAppropriateCommentsSection();

Regards,

**Comment by JamesHeinrich** [comment]
You say you added appropriate code, but you did not provide said code? It's much more likely to make it into getID3 if you submit the code you wrote (and a sample file).

**Comment by wagnered** [comment]
My apology.


added

  at line 248 	case 'tven': //TV Episode Name (id)

  at line 2180	$handyatomtranslatorarray['tven'] = 'tv_episode_name';


The smallest "sample" I could find is about 6.2 MB. I stepped through
Ampache and saw the tv_episode_name array available to Ampache.

Without those two lines, there was a warning that 'tven' was
unrecognized.


How would I get the file to you?


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by JamesHeinrich** [comment]
info@getid3.org would be easiest, thanks.

**Comment by JamesHeinrich** [comment]
Fixed in https://github.com/JamesHeinrich/getID3/commit/bf268b0bcd74e9a9b3f82ce77aca2e0ad38eeacf
