### ISSUE TITLE
libxml_disable_entity_loader is deprecated

### ISSUE THREAD

**Issue by rajpt** [JamesHeinrich/getID3#429]
Started getting this message recently i am using **php 8.1** and latest version of **getid3 1.9**

```
Function libxml_disable_entity_loader() is deprecated 
in /vendor/james-heinrich/getid3/getid3/getid3.lib.php on line 740
```

[PHP Doc](https://www.php.net/manual/en/function.libxml-disable-entity-loader.php)

**Comment by JamesHeinrich** [comment]
The documentation says it's deprecated, but doesn't give any specific examples of how it should be handled in PHP8.
I have made some changes in https://github.com/JamesHeinrich/getID3/commit/58b883d0bf279bad8e7c0bd432e10ad4711b23a0 , but if anyone can suggest a better way of handling it please let me know.

**Comment by JamesHeinrich** [comment]
It is released...

Or do you mean tagged as a Github release with a new version number?
