### ISSUE TITLE
Unable to determine .gpx file

### ISSUE THREAD

**Issue by tomswinkels** [JamesHeinrich/getID3#438]
Unable to determine .gpx file

```
array:7 [▼
  "GETID3_VERSION" => "1.9.23-202310190849"
  "filesize" => 57278
  "filepath" => "/tmp"
  "filename" => "phplYdzdi"
  "filenamepath" => "/tmp/phplYdzdi"
  "encoding" => "UTF-8"
  "error" => array:1 [▶
    0 => "unable to determine file format"
  ]
]
```

File: https://file.io/WDiq2DyWuaL9

**Comment by tomswinkels** [comment]
Maybe you can support .gpx?

**Comment by JamesHeinrich** [comment]
What would you expect getID3 to do with .gpx ?
GPX is just XML, so you can easily load it directly in PHP with something like
`$GPX = new SimpleXMLElement(file_get_contents($filename));`
see: https://www.php.net/manual/en/simplexml.examples-basic.php

**Comment by tomswinkels** [comment]
We use getID3 to get the mime type of files.

**Comment by JamesHeinrich** [comment]
Basic GPX format detection added in https://github.com/JamesHeinrich/getID3/commit/a94fb704aee97e9b9d7b461eda6dc022f44805ed
