### ISSUE TITLE
Strict Errors

### ISSUE THREAD

**Issue by romeosidvicious** [JamesHeinrich/getID3#44]
I'm getting these errors after moving to a new server, I've used this library for a long without any issues. I even have ~E_Strict turned off in php.ini but to no avail!

Strict Standards: Non-static method getid3_lib::IncludeDependency() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/getid3.php on line 266

Strict Standards: Non-static method getid3_lib::BigEndian2Int() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/module.tag.id3v2.php on line 99

Strict Standards: Non-static method getid3_lib::CastAsInt() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/getid3.lib.php on line 265

Strict Standards: Non-static method getid3_lib::trunc() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/getid3.lib.php on line 65

Strict Standards: Non-static method getid3_lib::BigEndian2Int() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/module.tag.id3v2.php on line 264

Strict Standards: Non-static method getid3_lib::CastAsInt() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/getid3.lib.php on line 265

Strict Standards: Non-static method getid3_lib::trunc() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/getid3.lib.php on line 65

Strict Standards: Non-static method getid3_lib::BigEndian2Int() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/module.tag.id3v2.php on line 283

Strict Standards: Non-static method getid3_lib::CastAsInt() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/getid3.lib.php on line 265

Strict Standards: Non-static method getid3_lib::trunc() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/getid3.lib.php on line 65

Strict Standards: Non-static method getid3_lib::CastAsInt() should not be called statically, assuming $this from incompatible context in /home/rsv/subdomains/mwbe/admin/includes/getid3/module.tag.id3v2.php on line 315

**Comment by JamesHeinrich** [comment]
Can you confirm you're using the latest version from Github (currently 1.9.9-20150318)?
https://github.com/JamesHeinrich/getID3/archive/master.zip

The line numbers you mention don't seem to correspond.

**Comment by romeosidvicious** [comment]
I may or may not have the issue, and I feel stupid. I just migrated everything to a new server and tested the migration of this site. However I didn't change the DNS yet. I am now waiting for the change to take affect. I doubt the problem still exists on the new server. Thanks for responding so quickly! I'll let you know if the problem exists once Comcasts caching name servers update. Thanks for the library, it's been very useful for a long time!
