### ISSUE TITLE
Caught exception: Uninitialized string offset 0

### ISSUE THREAD

**Issue by zyrouge** [JamesHeinrich/getID3#444]
I'm using [koel](https://github.com/koel/koel) and it seems like it could not parse some files. I'm not sure what the reason is except the below error message.

![image](https://github.com/JamesHeinrich/getID3/assets/50770114/ff2b6d20-b93f-4285-82f5-15728c9fdb98)

[This](https://cloud.akane.zyrouge.me/s/HrJSeusmrmjGdfu) is one of the file in which the error occurs.

**Comment by JamesHeinrich** [comment]
Your test file seems to work fine in the current version of getID3 (`1.9.23-202404261550`).  What version of getID3 is your installation using?  Most likely you're seeing a bug that was already fixed.

**Comment by zyrouge** [comment]
From what I could find, koel uses 1.9.21.

**Comment by JamesHeinrich** [comment]
You should be safe to download the latest build from github and overwrite wherever getID3 is installed for `koel`. Better yet, raise an issue with their developer and tell them to update their copy of getID3.

**Comment by zyrouge** [comment]
Tried with the latest version but it seems to be occurring with it too. Is it probably due to Docker? I'm not sure what the reason could be.

**Comment by zyrouge** [comment]
This is the stack trace of the error.
![image](https://github.com/JamesHeinrich/getID3/assets/50770114/d6bc9e31-aba1-4998-a0ff-417dbad53a5f)

**Comment by zyrouge** [comment]
Parsing the `lyrics-XXX` tag seems to be failing.

**Comment by JamesHeinrich** [comment]
Oh, actually you're right, when I look closer I do see a `Warning: Uninitialized string offset 0 in module.tag.id3v2.php on line 1071`

**Comment by JamesHeinrich** [comment]
Should be fixed in https://github.com/JamesHeinrich/getID3/commit/d0e347f9d501d184436b1c3dc35d0e7dbfada614
