### ISSUE TITLE
$getID3->setOption(array('option_tag_apetag' => false)); failing to switch off ape processing

### ISSUE THREAD

**Issue by janui** [JamesHeinrich/getID3#449]
Hello James,
In March 2024 I reported that on a 32 bit Linux environment many messages were produced 'Deprecated: Implicit conversion from float ... to int loses precision', its documented here: https://github.com/JamesHeinrich/getID3/issues/439
You shared a fix to switch of ape processing '$getID3->setOption(array('option_tag_apetag' => false));', which worked perfectly for me. Unfortunately the messages are back, switching off ape processing this way seems to have stopped working. Has the format of the command changed?

I am using:
To get the latest version of getID3: 'git clone -b master https://github.com/JamesHeinrich/getID3.git/ /home/getID3'
PHP: 8.2.7 (cli) (built: Jul 20 2023 18:02:54) (NTS)
Operating System: Raspbian GNU/Linux 12 (bookworm)
Kernel: Linux 6.6.28+rpt-rpi-v8

**Comment by JamesHeinrich** [comment]
Very little has changed in getID3 since then. Are you still getting errors on the same line numbers, or elsewhere?

**Comment by janui** [comment]
The line numbers are now different:
Aug 06 14:10:22 pi4 rune_MPDEM_wrk[30589]: Deprecated: Implicit conversion from float 2147483648 to int loses precision in /srv/http/app/libs/vendor/james-heinrich/getid3/getid3/module.tag.apetag.php on line 398
Aug 06 14:10:22 pi4 rune_MPDEM_wrk[30589]: Deprecated: Implicit conversion from float 2147483648 to int loses precision in /srv/http/app/libs/vendor/james-heinrich/getid3/getid3/module.tag.apetag.php on line 398
Aug 06 14:10:22 pi4 rune_MPDEM_wrk[30589]: Deprecated: Implicit conversion from float 2147483648 to int loses precision in /srv/http/app/libs/vendor/james-heinrich/getid3/getid3/module.tag.apetag.php on line 399
Aug 06 14:10:22 pi4 rune_MPDEM_wrk[30589]: Deprecated: Implicit conversion from float 2147483648 to int loses precision in /srv/http/app/libs/vendor/james-heinrich/getid3/getid3/module.tag.apetag.php on line 400
Aug 06 14:10:22 pi4 rune_MPDEM_wrk[30589]: Deprecated: Implicit conversion from float 2147483648 to int loses precision in /srv/http/app/libs/vendor/james-heinrich/getid3/getid3/module.tag.apetag.php on line 401
Aug 06 14:10:22 pi4 rune_MPDEM_wrk[30589]: Deprecated: Implicit conversion from float 2147483648 to int loses precision in /srv/http/app/libs/vendor/james-heinrich/getid3/getid3/module.tag.apetag.php on line 402

**Comment by JamesHeinrich** [comment]
I suspect that one of your files had a Lyrics3 tag, and that module will also call the apetag module to check for interaction (since they both appear in the same place at the end of a mp3 file, between audio data and ID3v1). The call to apetag module now respects the `getid3->option_tag_apetag` flag.
If this was your issue it should be fixed in https://github.com/JamesHeinrich/getID3/commit/c4f10f7c9d5e64622f01902d1e5dea4e62bae311
If not, please supply a sample file.

**Comment by janui** [comment]
Thats fixed it. Thanks for the incredibly fast work.
