### ISSUE TITLE
Roadmap for 2.0?

### ISSUE THREAD

**Issue by hassankhan** [JamesHeinrich/getID3#45]
Wanted to know if there's a roadmap for 2.0? Would like to contribute, but not sure where to start or what exactly is needed. Thanks :smile:

**Comment by JamesHeinrich** [comment]
I personally have no roadmap for 2.0

Other users have, over the years, put forth some effort and enthusiasm for a short time and made some progress towards the "2.0" release of the time, but nothing approaching a stable release has ever appeared.

I will continue to maintain v1.x indefinitely, but I have no ambitions to work on 2.0 myself (either coding or directing the effort).

**Comment by hassankhan** [comment]
Oh okay, I just saw the 2.0 branch and there seems to be some activity on it, is that official? Are there any roadmap/plans for that?

**Comment by duncan3dc** [comment]
Hi @hassankahn, I was working on the most recent 2.0 incarnation, but have since abandoned in favour of a new project that will focus on MP3 tagging: https://github.com/duncan3dc/meta-audio

Although it will be built in such a way that any format can be catered for without requiring the core to be changed

**Comment by hassankhan** [comment]
Hi, I'd prefer to use getID3 myself, since it does way more than just MP3 tagging. I've had a look at the 2.0 branch, and I do agree with the structure generally but there are a lot of changes I would make (not to mention time-consuming). I would love to have a crack at it to bring it up to speed, was just wondering if anyone else was interested?
