### ISSUE TITLE
TypeError When Processing the Bit Rate of a wav File

### ISSUE THREAD

**Issue by lihaohong6** [JamesHeinrich/getID3#458]
We got a `TypeError` when running getID3 on a wav file. The error message is `Unsupported operand types: string / int`. Below is the line that generated this error:

https://github.com/JamesHeinrich/getID3/blob/eb358a0d4943c0cc23e783f1a72141f46153c13a/getid3/module.audio.mp3.php#L308

Turns out that `$info['audio']['bitrate']` is "free" instead of a number. Elsewhere in the file, the program checks whether the bitrate is "free" before performing division on it. Perhaps an "if" statement was forgotten for this line?

Here's the (relevant) backtrace. `getID3` was invoked by [`TimedMediaHandler`](https://github.com/wikimedia/mediawiki-extensions-TimedMediaHandler/tree/master). I can provide the file that generated this error if needed. 
```
Backtrace:

from /srv/mediawiki/1.42/extensions/TimedMediaHandler/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(308)
#0 /srv/mediawiki/1.42/extensions/TimedMediaHandler/vendor/james-heinrich/getid3/getid3/module.audio-video.riff.php(1427): getid3_mp3->GuessEncoderOptions()
#1 /srv/mediawiki/1.42/extensions/TimedMediaHandler/vendor/james-heinrich/getid3/getid3/getid3.php(781): getid3_riff->Analyze()
#2 /srv/mediawiki/1.42/extensions/TimedMediaHandler/includes/Handlers/ID3Handler/ID3Handler.php(40): getID3->analyze(string)
#3 /srv/mediawiki/1.42/extensions/TimedMediaHandler/includes/Handlers/ID3Handler/ID3Handler.php(59): MediaWiki\TimedMediaHandler\Handlers\ID3Handler\ID3Handler->getID3(string)
#4 /srv/mediawiki/1.42/includes/media/MediaHandler.php(241): MediaWiki\TimedMediaHandler\Handlers\ID3Handler\ID3Handler->getMetadata(FSFile, string)
```

**Comment by JamesHeinrich** [comment]
A sample file would be very helpful. You can either post file or link here, or email to info@getid3.org if you don't want it public.

**Comment by lihaohong6** [comment]
Here are two files that result in an error: [Google Drive link](https://drive.google.com/drive/folders/1BXLqdBoaoMGj3AYmKz3C6l-ijPyU7N-K?usp=sharing)

These are reproduced by running a simple test script such as
```
require_once('getid3.php');
$gid = new getID3();
print_r($gid->analyze('test.wav'));
```

Curiously, if I convert a `wav` file to `ogg` and then back to `wav`, no error is thrown on the new `wav` file. However, going from `wav` to `flac` and then back to `wav` results in the same error, presumably because `flac` is lossless. Conversions are done with `ffmpeg`, so I would assume that the file header is standard-compliant.

**Comment by JamesHeinrich** [comment]
Thanks for the sample files, very helpful.
Should be fixed in https://github.com/JamesHeinrich/getID3/commit/39e5f54329779ebe04e2e666a98965f7f64a77f2
