### ISSUE TITLE
Add support for Shoutcast tags

### ISSUE THREAD

**Issue by marki555** [JamesHeinrich/getID3#46]
Add support for song name changes for mp3 files streamed via Shoutcast.
Protocol description: http://www.smackfu.com/stuff/programming/shoutcast.html

**Comment by JamesHeinrich** [comment]
getID3 analyzes files, not streams, I'm not sure how you'd propose implementing what you suggest.

**Comment by marki555** [comment]
By having the stream saved as mp3 file.
What I am trying to do is record few hours of the stream, then identify individual songs by the tags and divide the mp3 file based on that.
I just thought it was be a nice addition to your tool as it already supports many file & tag formats. Anyway, I have started working on simple parsing of these Shoutcast tags in php.

**Comment by JamesHeinrich** [comment]
Ah, I see. Feel free to submit a patch.
