### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by rajpt** [JamesHeinrich/getID3#460]
![image](https://github.com/user-attachments/assets/7b746a6e-1c0d-45ef-90e5-c66f38563569)

**Comment by JamesHeinrich** [comment]
Are you able to provide a sample file for testing?

**Comment by JamesHeinrich** [comment]
Should be fixed in https://github.com/JamesHeinrich/getID3/commit/8e5edc00b8be9007c511b00d3d4483a1ebe3a2ef

**Comment by rajpt** [comment]
Thank You @JamesHeinrich
