### ISSUE TITLE
Wrong mimetype for m4v files (video/quicktime)

### ISSUE THREAD

**Issue by tpinky** [JamesHeinrich/getID3#48]
The issue was first opened in:
https://github.com/ampache/ampache/issues/909

The wrong mime-type is assigned to m4v files.
In the database table "video" it is "video/quicktime" which is not correct. Should be "video/mp4". 
And not every browser supports quicktime as container.

During the scan following method is called:
GetFileFormat in getId3.php

The method iterates over a set of fileformat objects, that have a defined pattern field, which are checked with the header of the file(if it matches). Unfortunately it also matches with m4v files.

For quick time the entry is the following:
// QT - audio/video - Quicktime
'quicktime' => array(
'pattern' => '^.{4}(cmov|free|ftyp|mdat|moov|pnot|skip|wide)',
'group' => 'audio-video',
'module' => 'quicktime',
'mime_type' => 'video/quicktime',
)

**Comment by JamesHeinrich** [comment]
The MP4 (or, more properly, "ISO base media file format") is based on the QuickTime structure. About 90% of QuickTime, MP4, 3GPP, etc all overlap and have about 90% in common.
https://en.wikipedia.org/wiki/ISO_base_media_file_format

If you can propose an accurate test to differentiate MP4 from Quicktime from other cousins in the module.quicktime then I'll consider doing so.

**Comment by webkader** [comment]
hi, how do i fix this bug?

Declaration of getID3_cached_sqlite3::analyze() should be compatible with getID3::analyze($filename, $filesize = NULL, $original_filename = '') in extension.cache.sqlite3.php on line 265

i think here is the cause

public function analyze($filename) {
     ...
      $analysis = parent::analyze($filename);
     ...
}

**Comment by bhushanr** [comment]
Facing the same issue with the MIME type. Does this issue has been resolved?

**Comment by tpinky** [comment]
It isn't fixed.

**Comment by JamesHeinrich** [comment]
Again, if you can propose a test (other than based on filename) to differentiate a Quicktime container from a MP4 container I'll be happy to return video/mp4 where appropriate.

Meanwhile you can do something like
`$info['mime_type'] = ((($info['mime_type'] == 'video/quicktime') && preg_match('#\\.(mp4|m4v)$#i', $info['filename']) ? 'video/mp4' : $info['mime_type']);`
where $info is the array returned from getid3->analyze and that should modify the MIME type based on filename.

**Comment by tpinky** [comment]
As you said.
The specifications for quicktime and mp4 are very similar and each of them has around 150 sites?
To search for the differences seems to be a little bit time-consuming.
So I can't propose an accurate test at the moment.

**Comment by JamesHeinrich** [comment]
I made a change in https://github.com/JamesHeinrich/getID3/commit/9d46705999d26a635accce0c375162135b94bc79 that should set video/mp4 in some cases. If you have a file that should be showing as video/mp4 but still shows as video/quicktime with this change please let me know.
