### ISSUE TITLE
Declaration of getID3_cached_sqlite3

### ISSUE THREAD

**Issue by webkader** [JamesHeinrich/getID3#49]
hi, how do i fix this bug?

Declaration of getID3_cached_sqlite3::analyze() should be compatible with getID3::analyze($filename, $filesize = NULL, $original_filename = '') in extension.cache.sqlite3.php on line 265

i think here is the cause

public function analyze($filename) {
...
$analysis = parent::analyze($filename);
...
}

**Comment by JamesHeinrich** [comment]
Fixed in https://github.com/JamesHeinrich/getID3/commit/d5c2918a5769cb1a2ede1a083b05b8b82b77b2e5

Mirroring the similar fix (https://github.com/JamesHeinrich/getID3/commit/1e1f1a09958d7578e64f47090a4a91351db52618) in the MySQL cache extension, I have modified the parent::analyze call

**Comment by webkader** [comment]
thanks, next issue

SQLite3Stmt::execute(): Unable to execute statement: NOT NULL constraint failed: media_cache.filesize in extension.cache.sqlite3.php on line 195

**Comment by JamesHeinrich** [comment]
I am not familiar with SQLite, perhaps someone who is can comment and recommend a fix.

**Comment by webkader** [comment]
Fixed

Solution this line

return "CREATE TABLE IF NOT EXISTS $this->table (filename VARCHAR(255) NOT NULL DEFAULT '', dirname VARCHAR(255) NOT NULL DEFAULT '', filesize INT(11) NOT NULL DEFAULT '0', filetime INT(11) NOT NULL DEFAULT '0', analyzetime INT(11) NOT NULL DEFAULT '0', val text not null, PRIMARY KEY (filename, filesize, filetime))";

to

return "CREATE TABLE IF NOT EXISTS $this->table (filename VARCHAR(255) DEFAULT '', dirname VARCHAR(255) DEFAULT '', filesize INT(11) DEFAULT '0', filetime INT(11) DEFAULT '0', analyzetime INT(11) DEFAULT '0', val text, PRIMARY KEY (filename, filesize, filetime))";

**Comment by webkader** [comment]
sqlite allow the use of null entries in a primary key column. least one column of the primary key to be not null

**Comment by JamesHeinrich** [comment]
Taking your word for it, updated in https://github.com/JamesHeinrich/getID3/commit/de973d53e5887f734c3c40a62896ff49f6f736cc
