### ISSUE TITLE
open_base_dir restriction

### ISSUE THREAD

**Issue by avluis** [JamesHeinrich/getID3#52]
Can you consider changing this [line](https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.lib.php#L1168) to:

```php
$tempdir = sys_get_temp_dir();
```

My php install has an open_base_dir restriction in effect and generating album art using getID3 floods my command line with warnings - an example is provided [here](http://php.net/manual/en/function.tempnam.php#93256).

**Comment by JamesHeinrich** [comment]
I have implemented your suggestion, although not exactly as suggested, it should do what you want.
https://github.com/JamesHeinrich/getID3/commit/df7f782133e36da9345fd4d6ee639753831021fd

**Comment by avluis** [comment]
Actually, that's perfect - always making sure the function is there is a must - good call.
