### ISSUE TITLE
Multiple genres on AAC/M4A (quicktime) files treated as one tag

### ISSUE THREAD

**Issue by JoeDat** [JamesHeinrich/getID3#53]
Initially reported on Ampache github issue tracker
https://github.com/ampache/ampache/issues/970

Determined that mutliple genres, regardless of delimiter separator, are being treated as a single tag for quicktime audio files.  For example, a quicktime file tagged with genre 'Rock;Hard Rock;Metal' will display that tag availability as 'Rock;Hard Rock;Metal'.  

Confirmed that this same issue does not exist for MP3s.  MP3s using the same tagging convention will split the tags as expected.

**Comment by JamesHeinrich** [comment]
Can you provide a sample file I can look at?

**Comment by JoeDat** [comment]
Sure thing.  Shall I send it to 'info@silisoftware.com'?

**Comment by JamesHeinrich** [comment]
info@getid3.org would be more appropriate, thanks.

**Comment by JoeDat** [comment]
Sent two files, a functional mp3 and non-functional m4a.

**Comment by JamesHeinrich** [comment]
Both sample files had the same problem (multiple genre strings saved as a single semicolon-separated genre string). I have patched both ID3v2 and Quicktime modules to work around this. I don't believe it should have any unintended side effect on properly-written multiple genres, but let me know if it does.

Patched in https://github.com/JamesHeinrich/getID3/commit/a06585b732cf627589d23acd0f86d9cc6cdcb06f
