### ISSUE TITLE
Missing "break" in module.audio-video.quicktime.php ?

### ISSUE THREAD

**Issue by fretzl** [JamesHeinrich/getID3#60]
Not a coder so I'll just ask:
Shouldn't there be a `break;` after line 424 in module.audio-video.quicktime.php ?
Thanks.

**Comment by JamesHeinrich** [comment]
Yes, there should be. Thanks.
https://github.com/JamesHeinrich/getID3/commit/6d6791fd63c331b2ea5c5559815bf21a45535810
