### ISSUE TITLE
Files with UTF-16 TIT2 (and others) have invalid bytes before name

### ISSUE THREAD

**Issue by nicklan** [JamesHeinrich/getID3#61]
I have some files that have utf-16 titles.  When looking at them in demo.browse, the values get prefixed with invalid characters.  These show up as ? chars in my browser, but looking at the returned data, they are not valid utf-16 either.  For instance, for one file, the comments_html section contains:

    album 	array (1) 	0 	string (22) 	&#2089536;[correct subsequent characters for album]

This is for a number of different files, and other tools process the tags correctly.

Let me know if you need more info, or what else I can do to help track down what's wrong.  I'm on version 1.9.10-20150914

**Comment by JamesHeinrich** [comment]
A UTF-16 sample file would be a great start.

**Comment by nicklan** [comment]
Sure.  This file: http://datashat.net/music_for_programming_10-unity_gain_temple.mp3 (from http://musicforprogramming.net/) shows the problem.

Screenshot of what I'm seeing:
![2015-11-23-221744_1066x675_scrot](https://cloud.githubusercontent.com/assets/178912/11359373/4c2a4306-9230-11e5-92cf-8ff0d5b4812c.png)

and output of id3v2 -l:
![2015-11-23-221905_893x102_scrot](https://cloud.githubusercontent.com/assets/178912/11359379/56fc32e4-9230-11e5-8b30-a435cd2755d2.png)

**Comment by JamesHeinrich** [comment]
Those non-displayable characters are indeed the [Byte Order Marker (BOM)](https://en.wikipedia.org/wiki/Byte_order_mark) from the UTF-16 text.

The [ID3 documentation](http://id3.org/id3v2.4.0-structure) specifies this regarding text encodings:
    Frames that allow different types of text encoding contains a text
    encoding description byte. Possible encodings:
    
     $00   ISO-8859-1 [ISO-8859-1]. Terminated with $00.
     $01   UTF-16 [UTF-16] encoded Unicode [UNICODE] with BOM. All
           strings in the same frame SHALL have the same byteorder.
           Terminated with $00 00.
     $02   UTF-16BE [UTF-16] encoded Unicode [UNICODE] without BOM.
           Terminated with $00 00.
     $03   UTF-8 [UTF-8] encoded Unicode [UNICODE]. Terminated with $00.
    
    Strings dependent on encoding are represented in frame descriptions
    as <text string according to encoding>, or <full text string
    according to encoding> if newlines are allowed. Any empty strings of
    type $01 which are NULL-terminated may have the Unicode BOM followed
    by a Unicode NULL ($FF FE 00 00 or $FE FF 00 00).

Your file is tagged with encoding 01 "UTF-16" which means the text could be either big-endian or little-endian, as determined by the BOM at the start of the string. Without the BOM it is unknown how to display (or convert) the text since it's not known what order the bytes come in. With encoding 02 "UTF-16BE" the order is known so the BOM is not needed.

I did make a small change to remove the BOM from blank frame description fields (which are usually blank). The BOM will remain for non-empty description as well as the actual data.
https://github.com/JamesHeinrich/getID3/commit/88d284f7a2dbc014fe349e4efdb41d73faa0eb34

Normally you would pull the comment data you need from $info['comments']['title'] rather than $info['id3v2']['COMM'][0]['data'] and the data there is (by default) already converted to UTF-8 which intrinsically removes the BOM. If you do need to process your data directly in UTF-16 for whatever reason then you would need the BOM intact otherwise your string couldn't be handled.

**Comment by nicklan** [comment]
Ahh yes, this makes sense.  Can I ask then though, why $info['comments']['title'] seems to be an array of two elements, one without the BOM but shortened, and one still with the BOM (i assume) but all the rest of text.  See below:
![2015-11-24-150841_902x363_scrot](https://cloud.githubusercontent.com/assets/178912/11383496/65f5d4d4-92bd-11e5-8f2f-e68f58d3f010.png)

**Comment by JamesHeinrich** [comment]
That shouldn't be. There should only be one instance of each title without the BOM. Please check that you've mirrored all the changes from Github.

![g61](https://cloud.githubusercontent.com/assets/3483435/11383986/f2e7e0f0-92d9-11e5-9057-dc772966e013.png)

**Comment by nicklan** [comment]
I have the latest version and I'm still seeing the same as above.  I made a fresh checkout of the repo, and at the bottom of the page I see "Powered by getID3() v1.9.10-201511241457" which seems to be the latest version.

**Comment by nicklan** [comment]
Well, I think I know why there are two things, seems like one is coming from the id3v1 tag (the shortened one) and one from the id3v2 tag (with the BOM).  You probably already figure that :)  But I'm still not sure why you're not seeing that behavior.  Could there be something in my php settings?  I'm on 5.6.4 64-bit.

**Comment by JamesHeinrich** [comment]
My best guess would be that your PHP installation doesn't have native [iconv()](http://www.php.net/manual/en/function.iconv.php) support and it's relying on [getid3_lib::iconv_fallbac()](https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.lib.php#L957-L1003) and there may be an issue in there.

Note that this is simply a guess at this point, I'll need to take a look at that tomorrow and see if I can find a problem. I'll let you know.

**Comment by JamesHeinrich** [comment]
Can you save the entire output of demo.browse for that file to a .html file and attach it here please?

**Comment by nicklan** [comment]
Sure, attached below (as .txt so github would let me).  I'll have a look too and see if I can figure anything out with the iconv thing, thanks for the hint.

[getID3() - _demo_demo.browse.php (sample script).txt](https://github.com/JamesHeinrich/getID3/files/43547/getID3.-._demo_demo.browse.php.sample.script.txt)

**Comment by JamesHeinrich** [comment]
If I disable the built-in iconv and use getID3's version it still works correctly. Perhaps there is an issue with your built-in version of iconv?

First let's check if it's there, what version if available, and then try a very simple conversion using both PHP's iconv() function and getID3's version:

    echo (function_exists('iconv') ? 'yes: '.`iconv --version` : 'no').'<hr>';
    $string = "\xFF\xFE\x48\x00\x69\x00"; // BOM+"Hi"
    echo iconv('UTF-16', 'UTF-8//TRANSLIT', $string).'<br>';
    require_once('/path/to/getid3/getid3.lib.php');
    echo getid3_lib::iconv_fallback('UTF-16', 'UTF-8//TRANSLIT', $string).'<br>';

They should both just say "Hi" with no BOM, 2 chars long. I suspect one of them will be 4-chars with a BOM.

**Comment by nicklan** [comment]
Yep, looks like iconv is failing and the builtin one is leaving the BOM:

```
yes: iconv (Gentoo 2.21-r1 p5) 2.21
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Ulrich Drepper.
bool(false)
string(6) "��Hi"
```

**Comment by nicklan** [comment]
ahh, and iconv error is: "Notice: iconv(): Wrong charset, conversion from `UTF-16' to `UTF-8//TRANSLIT' is not allowed in [path_to_test].php on line 13" (the iconv line)

**Comment by nicklan** [comment]
couple of other notes

- on the command line, iconv seems to be able to convert from utf-16 to utf-8 without a problem (i.e. not going through php).  not sure if that's at all relevant but I wanted to test.

- i've tried UTF-8//IGNORE and UTF-8 with the same results

**Comment by nicklan** [comment]
ohh, and if i run php at the command line, it works.  outputting:

```
<pre>yes: iconv (Gentoo 2.21-r1 p5) 2.21
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Ulrich Drepper.
<hr>string(2) "Hi"
string(2) "Hi"
```

So it must be something with my nginx install.  Yar.  I will keep hunting.

**Comment by nicklan** [comment]
Okay, turned out to be an issue with php-fpm which wasn't loading the iconv shared libraries properly.  Thanks for the help pin-pointing it!
