### ISSUE TITLE
Small oversight in module.audio-video.quicktime.php ?

### ISSUE THREAD

**Issue by fretzl** [JamesHeinrich/getID3#63]
Nothing serious, just a question ;-)
Lines 378 and 380 *tven* and *tvnn* should maybe appear somewhere between lines 502 and 507 for completeness ?

Sorry for committing an empty issue at first.

**Comment by JamesHeinrich** [comment]
You didn't write anything.

**Comment by fretzl** [comment]
Wow, that's fast !
Sorry for committing an empty issue at first ! I just edited the issue.

**Comment by JamesHeinrich** [comment]
No, I don't believe so. Those keys should be of type UTF8-string, not integer, so they should end up being processed on [line 516](https://github.com/JamesHeinrich/getID3/blob/master/getid3/module.audio-video.quicktime.php#L516)

If you have a sample file with these fields present I would be interested.

**Comment by fretzl** [comment]
Sorry to have bothered you without sufficient knowledge !
I *thought* I saw some inconsistency.
I did get a sample file from one of our users (Zenphoto) with a number of tags.
One of the tags is *tven* (tv_episode_id) and that actually works ;-)
Anyway, thanks for your patience!

**Comment by JamesHeinrich** [comment]
No worries, I'd rather confirm it's not a bug than you not report it :)
