### ISSUE TITLE
Working with temp files

### ISSUE THREAD

**Issue by thegoodson** [JamesHeinrich/getID3#67]
The following functions in PHP fail to provide the correct result with files created using `tempnam(…)` function
 - is_readable
 - is_writeable

Imagine a file is being read into a tempfile from the internet, getID3 will fail to process it.

_PHP 5.5.30_

**Comment by JamesHeinrich** [comment]
Is this bug documented somewhere? Is it specific to PHP 5.5(.30)?

A quick test on PHP 5.3.3 (*nix) and PHP 5.4.7 (Win) showed no problems:
`echo (is_readable($filename = tempnam('/tmp','getid3')) ? '' : 'not-').'readable: '.$filename;`
What does that line of code output for you?

**Comment by thegoodson** [comment]
It outputs `false` for me.
For `is_readable` and `is_writeable`, `is_file` works fine.
I came across the error on Google App Engine, where I host my application.

I have only tried this out on PHP 5.5.X.
I'll find time later on to break down the issue, but this is the result I've gotten so far.

**Comment by JamesHeinrich** [comment]
"false" is an unexpected output from that line -- it should say either readable or not-readable and confirmation of the temp filename that's generated. Perhaps this code is more explicit:

    $filename = tempnam('/tmp', 'foo');
    echo 'filename: '.$filename.'<br>';
    echo (is_readable($filename) ? 'readable' : 'not-readable').'<br>';
    echo (is_writeable($filename) ? 'writeable' : 'not-writeable').'<br>';
    unlink($filename);

When you have time later to do some debugging it would be appreciated. After a few minutes of searching I can't find any other reports of the problem you describe with tempnam.

At this point my speculation is that tempnam() is returning false for you. getID3 attempts to auto-detect the appropriate system temp directory in which to create temp files, but if that's failing for you there is an override line you can uncomment in [getid3.php line 63](https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L63) where you can enter a temp directory you do have read/write access to.

**Comment by thegoodson** [comment]
Sorry about that, my response was the `bool` value of `is_writeable`. I didn't explicitly run your code block.

Anyways, I ran a full test, the temp file can we written, read and copied to a different location, and so on, but will always return `false` from the two highlighted functions.

Here's the result from your code block as well.
```
filename: vfs://root/temp//tmp/foo56cb16f2992517.13579214
not-readable
not-writeable
```

**Comment by JamesHeinrich** [comment]
I think `filename: vfs://...` is the key issue here.

Your analysis and code suggestions are welcome.

**Comment by JamesHeinrich** [comment]
Closing issue for now. If you have future analysis or suggestions you wish to post, please do so.
