### ISSUE TITLE
Arrays not working to write

### ISSUE THREAD

**Issue by dariomehr** [JamesHeinrich/getID3#70]
demos/demo.simple.write.php (line 48):
'popularimeter' => array('email'=>'user@example.net', 'rating'=>128, 'data'=>0),

Always throw:
WriteID3v2() failed with message(s):
    [email] not specified for POPM
    Frame "POPM" is NOT allowed
    $this->GenerateID3v2FrameData() failed for "POPM"
    $this->GenerateID3v2Tag() failed

Too for 'unique_file_identifier', never find 'ownerid'

**Comment by JamesHeinrich** [comment]
POPM fixed in https://github.com/JamesHeinrich/getID3/commit/29fdb2dbc9eb18b3bfde9bc521ecabbdfe657646

**Comment by JamesHeinrich** [comment]
UFID fixed in https://github.com/JamesHeinrich/getID3/commit/09a1b9e960ebc4c1288afc46ec2ff1e9cb926d9b
