### ISSUE TITLE
get info from url

### ISSUE THREAD

**Issue by hamedmoody** [JamesHeinrich/getID3#78]
Hi
can i get mp4 info from external url?

**Comment by JamesHeinrich** [comment]
No. getID3 only operates on local files. You'll need to copy (some or all of) your remote file locally for analysis. See http://www.getid3.org/phpBB3/viewtopic.php?t=1605 for more details.

**Comment by mikeshiyan** [comment]
Does the getid3.org work? I see apache default page only.

**Comment by mikeshiyan** [comment]
Just found the resource in Internet Archive - https://web.archive.org/web/20160727231226/http://www.getid3.org/phpBB3/viewtopic.php?t=1605

But it just describes methods to copy remote file, and not the answer why the library does not allow to work with remote files. What are the reasons behind this?

**Comment by JamesHeinrich** [comment]
getID3.org works just fine.
getID3 requires the file locally because it generally involves a lot of seeking to specific offsets to find the needed data.

**Comment by mikeshiyan** [comment]
But that is also possible with URLs and other PHP stream wrappers. They can be fopened, fsought and fread as long as stream wrapper is registered.

**Comment by hamedmoody** [comment]
I use HTML5 video tag in clientside and get metadata instead it.
So thanks
