### ISSUE TITLE
Composer autoload classmap incomplete

### ISSUE THREAD

**Issue by Preau** [JamesHeinrich/getID3#83]
The autoload classmap in your composer.json file is very incomplete.

It is hard to use getid3_writetags for example when using the Composer installation.

Can you maybe add at least write.php (but best would be all classes) to the classmap.

**Comment by JamesHeinrich** [comment]
Please feel free to submit a modified composer.json and I can merge it.

**Comment by JamesHeinrich** [comment]
Possibly fixed with https://github.com/JamesHeinrich/getID3/pull/86
