### ISSUE TITLE
Error Write

### ISSUE THREAD

**Issue by gendhenk** [JamesHeinrich/getID3#85]
Hello 
I use the latest version, but errors as follows
"Fatal error: Uncaught exception 'Exception' with message '$this->overwrite_tags=false is known to be buggy in this version of getID3. Will be fixed in the near future, check www.getid3.org for a newer version...."

**Comment by JamesHeinrich** [comment]
Yes. getID3 tag writing is generally in an alpha state, and overwrite_tags has had reports of corrupted files for reasons I haven't discovered and should probably not be used.

Unfortunately I have no plans of rewriting the ID3v2-writing section of getID3 anytime soon (or at all) so this falls under "won't fix".
