### ISSUE TITLE
Uses obsolete mysql_pconnect function

### ISSUE THREAD

**Issue by pleia2** [JamesHeinrich/getID3#90]
The mysql_pconnect function was deprecated in PHP 5.5.0, and it was removed in PHP 7.0.0, which is now shipping with most modern Linux distributions. It's still being used in getid3/extension.cache.mysql.php so while assisting with a website upgrade we're running into problems.

**Comment by JamesHeinrich** [comment]
Just switch to extension.cache.mysqli.php instead
