### ISSUE TITLE
[QUESTION] possible to use MCDI/music_cd_identifier for freedb lookup?

### ISSUE THREAD

**Issue by othmar52** [JamesHeinrich/getID3#96]
I have a lot of albums with id3v2 `music_cd_identifier`.
An example value of getid3 looks like that
```
16+96+27DF+54AB+6FC4+9A26+BC59+D88D+1077F+12F11+1515A+17423+19D95+1BE6D+1DCB0+204F1+23A4B+256B1+2787B+29AA1+2B886+2CB93+2ED03+313C1
```

Shouldn't the stored data represent:

* 32-bit hex CDDB disc-id. The first byte of this is the track checksum, the
 next two are the length of the CD in seconds, and the last is the number
 of tracks
* Number of tracks
* Frame offset of each track
* Second offset for the leadout track (length of the CD in seconds)

taken from https://github.com/taem/cd-discid/blame/master/README.md#L5-L27

i wondered if the value returned by getID3 can be converted to perform a cddb lookup!?

Or do you have any other usecases in mind that gives some benefit to an existing `music_cd_identifier`

**Comment by JamesHeinrich** [comment]
I have no usecases in mind. I don't have any sample files with the `music_cd_identifier` field either, if you could provide one.

How would you like `music_cd_identifier` transformed? Please provide an example input and output that you think would be useful.

**Comment by othmar52** [comment]
[Here](https://github.com/JamesHeinrich/getID3/files/756874/01.Skip.It.mp3.zip) is a testfile which was ripped yesterday by a mate of me with "Windows Media Player".
My research which lookup service WMP is using was not succesful but i assume it uses either "gracenote" or "freedb" for its lookup.

For now i am not able to tell which format for getID3's output of `MCDI` would make sense but i will do some further investigation. My idea is to do some network sniffing during ripping. As i don't have any experience with sniffing it may will take a little while...

**Comment by JamesHeinrich** [comment]
getID3 simply reports the text string stored in the ID3v2 tag. It makes no special effort to interpret it.

Since this is probably outside the purview of getID3 I'm going to close this issue now, but if you come up with some code for interpreting or reformatting that value in a useful way please feel free to post back here since others in the future may be interested. If you think having getID3 do additional parsing using your code, please reopen the issue at that time.
